name: "Fallback Orchestrator Workflow"
run-name: "🚀 Fallback Orchestrator | rossy8417"

on:
  workflow_dispatch:
    inputs:
      concept:
        description: 'Concept'
        required: true
        type: string

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Fallback Execution
        run: echo "Fallback orchestrator executed"
