name: image-analysis
description: 画像分析の最小単位ユニット

on:
  workflow_call:
    inputs:
      analysis_target:
        description: '分析対象タイプ（image, photo, artwork, diagram, etc.）'
        required: false
        type: string
        default: 'image'
      image_path:
        description: '分析する画像パス'
        required: true
        type: string
      output_dir:
        description: '出力ディレクトリパス'
        required: true
        type: string
      analysis_type:
        description: '分析タイプ（general/object/face/text）'
        required: false
        type: string
        default: 'general'
      detail_level:
        description: '詳細レベル（basic/detailed/comprehensive）'
        required: false
        type: string
        default: 'detailed'
    outputs:
      analysis_result:
        description: '分析結果'
        value: ${{ jobs.analyze.outputs.analysis_result }}
      analysis_path:
        description: '分析結果ファイルパス'
        value: ${{ jobs.analyze.outputs.analysis_path }}
      detected_objects:
        description: '検出されたオブジェクト数'
        value: ${{ jobs.analyze.outputs.detected_objects }}
    secrets:
      anthropic_api_key:
        description: 'Anthropic API Key'
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    outputs:
      analysis_result: ${{ steps.execute.outputs.analysis_result }}
      analysis_path: ${{ steps.execute.outputs.analysis_path }}
      detected_objects: ${{ steps.execute.outputs.detected_objects }}
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Claude Code SDK
        run: npm install @anthropic-ai/claude-code
      
      - name: Analyze Image
        id: execute
        env:
          ANTHROPIC_API_KEY: ${{ secrets.anthropic_api_key }}
        run: |
          # ディレクトリ作成
          mkdir -p "${{ inputs.output_dir }}"
          
          # 分析プロンプトの構築
          ANALYSIS_TARGET="${{ inputs.analysis_target }}"
          
          ANALYSIS_PROMPT="Analyze the ${ANALYSIS_TARGET} at '${{ inputs.image_path }}' with the following requirements:

          Analysis Type: ${{ inputs.analysis_type }}
          Detail Level: ${{ inputs.detail_level }}

          Please provide:
          1. Overall description of the ${ANALYSIS_TARGET}
          2. Key visual elements and their positions
          3. Colors, lighting, and composition
          4. Detected objects or subjects in the ${ANALYSIS_TARGET}
          5. Technical quality assessment
          6. Suggested improvements or observations

          Save the analysis as a structured JSON file to '${{ inputs.output_dir }}/analysis.json' with the following format:
          {
            \"summary\": \"Brief overall description\",
            \"visual_elements\": [],
            \"colors\": [],
            \"objects\": [],
            \"technical_quality\": {},
            \"suggestions\": []
          }"
          
          # Claude Code実行
          npx @anthropic-ai/claude-code \
            --allowedTools "Read,Write" \
            --max-turns 10 \
            --permission-mode "acceptEdits" \
            -p "$ANALYSIS_PROMPT"
          
          # 結果確認
          if [ -f "${{ inputs.output_dir }}/analysis.json" ]; then
            # 分析結果を読み込み
            ANALYSIS=$(cat "${{ inputs.output_dir }}/analysis.json" | jq -c .)
            OBJECT_COUNT=$(cat "${{ inputs.output_dir }}/analysis.json" | jq '.objects | length')
            
            echo "analysis_result=$ANALYSIS" >> $GITHUB_OUTPUT
            echo "analysis_path=${{ inputs.output_dir }}/analysis.json" >> $GITHUB_OUTPUT
            echo "detected_objects=$OBJECT_COUNT" >> $GITHUB_OUTPUT
          else
            # フォールバック
            echo "{\"error\": \"Analysis failed\"}" > "${{ inputs.output_dir }}/analysis.json"
            echo "analysis_result={\"error\": \"Analysis failed\"}" >> $GITHUB_OUTPUT
            echo "analysis_path=${{ inputs.output_dir }}/analysis.json" >> $GITHUB_OUTPUT
            echo "detected_objects=0" >> $GITHUB_OUTPUT
          fi