name: "🎯 Dynamic Workflow - Issue #62"
run-name: "📊 Dynamic | rossy8417 | Issue #62"

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Source issue number"
        required: true
        default: "62"
      branch_name:
        description: "Working branch name"
        required: false
        default: "issue-62"

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

env:
  CLAUDE_CODE_CI_MODE: true
  CLAUDE_CODE_AUTO_APPROVE_MCP: true
  CLAUDE_CODE_OAUTH_TOKEN: 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

jobs:
  setup:
    name: "🚀 Setup"
    runs-on: ubuntu-latest
    outputs:
      project_dir: 
      timestamp: 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Project Structure
        id: setup
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          PROJECT_DIR="projects/issue-62-$TIMESTAMP"
          mkdir -p "$PROJECT_DIR"/{logs,metadata,temp,final,media}
          echo "project_dir=$PROJECT_DIR" >> $GITHUB_OUTPUT
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "✅ Project structure created: $PROJECT_DIR"

  planning_1:
    name: "📋 Planning: content-planning"
    uses: ./minimal-units/planning/planning-ccsdk.yml
    needs: setup
    with:
      concept: "Issue #62"
      output_dir: "/metadata"
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: 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

  planning_2:
    name: "📋 Planning: narration-creation"
    uses: ./minimal-units/planning/planning-ccsdk.yml
    needs: planning_1
    with:
      concept: "Issue #62"
      output_dir: "/metadata"
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: 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

  planning_3:
    name: "📋 Planning: scene-composition"
    uses: ./minimal-units/planning/planning-ccsdk.yml
    needs: planning_2
    with:
      concept: "Issue #62"
      output_dir: "/metadata"
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: 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

  image_generation:
    name: "🎨 image-generation"
    uses: ./minimal-units/media/image/t2i-imagen3.yml
    needs: planning_3
    with:
      prompt: "Generated content for issue #62"
      output_dir: "/media"
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: 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

  text_to_speech:
    name: "🎨 text-to-speech"
    runs-on: ubuntu-latest
    needs: planning_3
    with:
      prompt: "Generated content for issue #62"
      output_dir: "/media"
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: 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

  video_generation:
    name: "🎨 video-generation"
    uses: ./minimal-units/media/video/t2v-veo3.yml
    needs: planning_3
    with:
      prompt: "Generated content for issue #62"
      output_dir: "/media"
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: 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

  post_1:
    name: "🔧 Post: lipsync"
    runs-on: ubuntu-latest
    needs: [image_generation, text_to_speech, video_generation]
    with:
      video_list: "placeholder"
      output_dir: "/final"

  post_2:
    name: "🔧 Post: subtitle-overlay"
    uses: ./minimal-units/postprod/subtitle-overlay.yml
    needs: post_1
    with:
      video_list: "placeholder"
      output_dir: "/final"

  summary:
    name: "📊 Summary"
    runs-on: ubuntu-latest
    if: always()
    needs: [setup, planning_1, planning_2, planning_3, image_generation, text_to_speech, video_generation, post_1, post_2]
    steps:
      - name: Generate Summary
        run: |
          echo "# 🎯 Workflow Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Issue**: #62" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: Completed" >> $GITHUB_STEP_SUMMARY
          echo "- **Project**: " >> $GITHUB_STEP_SUMMARY
