name: "Blog Article Creation Workflow"
run-name: "ðŸ“ Creating blog article: ${{ github.event.inputs.keywords || 'Blog Article Creation' }}"

on:
  workflow_dispatch:
    inputs:
      keywords:
        description: 'ãƒ¡ã‚¤ãƒ³ã‚­ãƒ¼ãƒ¯ãƒ¼ãƒ‰ãƒ»ãƒ†ãƒ¼ãƒž'
        required: true
        default: 'WordPress SEOå¯¾ç­–ã€ãƒªãƒ¢ãƒ¼ãƒˆãƒ¯ãƒ¼ã‚¯ç”Ÿç”£æ€§å‘ä¸Šã€Pythonåˆå¿ƒè€…å­¦ç¿’'
        type: string
      article_type:
        description: 'è¨˜äº‹ã®ç¨®é¡žãƒ»ã‚¹ã‚¿ã‚¤ãƒ«'
        required: true
        type: choice
        options:
        - how_to_guide
        - list_article
        - case_study
        - opinion_editorial
        - news_analysis
        - review_comparison
        default: 'how_to_guide'
      target_audience:
        description: 'ã‚¿ãƒ¼ã‚²ãƒƒãƒˆèª­è€…'
        required: true
        type: choice
        options:
        - beginners
        - intermediate
        - advanced
        - business_professionals
        - general_public
        default: 'intermediate'
      content_length:
        description: 'è¨˜äº‹ã®é•·ã•'
        required: true
        type: choice
        options:
        - short
        - medium
        - long
        - comprehensive
        default: 'medium'
      seo_focus:
        description: 'SEOæœ€é©åŒ–ãƒ¬ãƒ™ãƒ« (1-10)'
        required: true
        default: '7'
        type: choice
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        - '7'
        - '8'
        - '9'
        - '10'

permissions:
  contents: write
  issues: read
  actions: read

env:
  CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

jobs:
  # Phase 1: ã‚­ãƒ¼ãƒ¯ãƒ¼ãƒ‰åˆ†æž
  keyword-analysis:
    runs-on: ubuntu-latest
    outputs:
      analysis_ready: ${{ steps.analyze.outputs.analysis_ready }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Analyze keywords and SEO strategy
        id: analyze
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "ðŸ” Analyzing keywords and SEO strategy..."
          
          mkdir -p .logs/keyword-analysis
          
          KEYWORDS="${{ github.event.inputs.keywords }}"
          SEO_FOCUS="${{ github.event.inputs.seo_focus }}"
          
          claude-code --prompt "ä»¥ä¸‹ã®ã‚­ãƒ¼ãƒ¯ãƒ¼ãƒ‰ã‚’åŸºã«ã€SEOæˆ¦ç•¥ã¨ã‚­ãƒ¼ãƒ¯ãƒ¼ãƒ‰åˆ†æžã‚’è¡Œã£ã¦ãã ã•ã„ï¼š
          
          ã‚­ãƒ¼ãƒ¯ãƒ¼ãƒ‰: $KEYWORDS
          SEOé‡ç‚¹åº¦: $SEO_FOCUS/10
          
          JSONå½¢å¼ã§ã‚­ãƒ¼ãƒ¯ãƒ¼ãƒ‰åˆ†æžçµæžœã‚’è¿”ã—ã¦ãã ã•ã„ã€‚" > .logs/keyword-analysis/keyword-analysis.json
          
          echo "analysis_ready=true" >> $GITHUB_OUTPUT
          echo "ðŸ” Keyword analysis completed"

  # Phase 2: è¨˜äº‹æ§‹æˆè¨­è¨ˆ
  content-structure:
    needs: keyword-analysis
    runs-on: ubuntu-latest
    outputs:
      structure_ready: ${{ steps.structure.outputs.structure_ready }}
    steps:
      - name: Design article structure
        id: structure
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "ðŸ“‹ Designing article structure..."
          
          mkdir -p .logs/content-structure
          
          ARTICLE_TYPE="${{ github.event.inputs.article_type }}"
          TARGET_AUDIENCE="${{ github.event.inputs.target_audience }}"
          CONTENT_LENGTH="${{ github.event.inputs.content_length }}"
          
          claude-code --prompt "ä»¥ä¸‹ã®æ¡ä»¶ã§è¨˜äº‹æ§‹æˆã‚’è¨­è¨ˆã—ã¦ãã ã•ã„ï¼š
          
          è¨˜äº‹ã‚¿ã‚¤ãƒ—: $ARTICLE_TYPE
          ã‚¿ãƒ¼ã‚²ãƒƒãƒˆ: $TARGET_AUDIENCE
          è¨˜äº‹ã®é•·ã•: $CONTENT_LENGTH
          
          JSONå½¢å¼ã§è¨˜äº‹æ§‹æˆã‚’è¿”ã—ã¦ãã ã•ã„ã€‚" > .logs/content-structure/article-structure.json
          
          echo "structure_ready=true" >> $GITHUB_OUTPUT
          echo "ðŸ“‹ Article structure design completed"

  # Phase 3: ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ç”Ÿæˆ
  content-generation:
    needs: [keyword-analysis, content-structure]
    runs-on: ubuntu-latest
    outputs:
      content_ready: ${{ steps.generate.outputs.content_ready }}
    steps:
      - name: Generate article content
        id: generate
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "âœï¸ Generating article content..."
          
          mkdir -p .logs/content-generation
          
          KEYWORDS="${{ github.event.inputs.keywords }}"
          ARTICLE_TYPE="${{ github.event.inputs.article_type }}"
          TARGET_AUDIENCE="${{ github.event.inputs.target_audience }}"
          
          claude-code --prompt "ä»¥ä¸‹ã®æ¡ä»¶ã§ãƒ–ãƒ­ã‚°è¨˜äº‹ã‚’ç”Ÿæˆã—ã¦ãã ã•ã„ï¼š
          
          ã‚­ãƒ¼ãƒ¯ãƒ¼ãƒ‰: $KEYWORDS
          è¨˜äº‹ã‚¿ã‚¤ãƒ—: $ARTICLE_TYPE
          ã‚¿ãƒ¼ã‚²ãƒƒãƒˆèª­è€…: $TARGET_AUDIENCE
          
          å®Œå…¨ãªãƒ–ãƒ­ã‚°è¨˜äº‹ã‚’Markdownå½¢å¼ã§ç”Ÿæˆã—ã¦ãã ã•ã„ã€‚" > .logs/content-generation/article-content.md
          
          echo "content_ready=true" >> $GITHUB_OUTPUT
          echo "âœï¸ Article content generation completed"

  # Phase 4: SEOæœ€é©åŒ–
  seo-optimization:
    needs: content-generation
    runs-on: ubuntu-latest
    outputs:
      seo_ready: ${{ steps.optimize.outputs.seo_ready }}
    steps:
      - name: Optimize for SEO
        id: optimize
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "ðŸš€ Optimizing for SEO..."
          
          mkdir -p .logs/seo-optimization
          
          SEO_FOCUS="${{ github.event.inputs.seo_focus }}"
          
          claude-code --prompt "ç”Ÿæˆã•ã‚ŒãŸè¨˜äº‹ã‚’SEOæœ€é©åŒ–ã—ã¦ãã ã•ã„ã€‚
          
          SEOé‡ç‚¹åº¦: $SEO_FOCUS/10
          
          JSONå½¢å¼ã§SEOæœ€é©åŒ–ãƒ¬ãƒãƒ¼ãƒˆã‚’è¿”ã—ã¦ãã ã•ã„ã€‚" > .logs/seo-optimization/seo-report.json
          
          echo "seo_ready=true" >> $GITHUB_OUTPUT
          echo "ðŸš€ SEO optimization completed"

  # Phase 5: æœ€çµ‚ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ä½œæˆ
  final-packaging:
    needs: [keyword-analysis, content-structure, content-generation, seo-optimization]
    runs-on: ubuntu-latest
    steps:
      - name: Create blog article package
        run: |
          echo "ðŸ“¦ Creating blog article package..."
          
          mkdir -p .final-output/{analysis,content,seo}
          
          # ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆæ–‡æ›¸
          cp .logs/keyword-analysis/keyword-analysis.json .final-output/analysis/ 2>/dev/null || true
          cp .logs/content-structure/article-structure.json .final-output/analysis/ 2>/dev/null || true
          
          # ã‚³ãƒ³ãƒ†ãƒ³ãƒ„æˆæžœç‰©
          cp .logs/content-generation/article-content.md .final-output/content/ 2>/dev/null || true
          cp .logs/seo-optimization/seo-report.json .final-output/seo/ 2>/dev/null || true
          
          # ãƒžã‚¹ã‚¿ãƒ¼ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆæƒ…å ±
          cat > .final-output/blog-project-master.json << EOF
          {
            "project_info": {
              "project_name": "Blog Article Creation",
              "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
              "github_run_id": "${{ github.run_id }}",
              "project_type": "seo_optimized_blog_article"
            },
            "input_parameters": {
              "keywords": "${{ github.event.inputs.keywords }}",
              "article_type": "${{ github.event.inputs.article_type }}",
              "target_audience": "${{ github.event.inputs.target_audience }}",
              "content_length": "${{ github.event.inputs.content_length }}",
              "seo_focus": ${{ github.event.inputs.seo_focus }}
            },
            "deliverables": {
              "analysis": {
                "keyword_analysis": "analysis/keyword-analysis.json",
                "article_structure": "analysis/article-structure.json"
              },
              "content": {
                "blog_article": "content/article-content.md"
              },
              "seo": {
                "seo_report": "seo/seo-report.json"
              }
            }
          }
          EOF
          
          echo "ðŸ“¦ Blog article package created"
          
      - name: Upload Blog Article Package
        uses: actions/upload-artifact@v4
        with:
          name: blog-article-package-${{ github.run_number }}
          path: .final-output/
          retention-days: 30