name: "Presentation Slide Creation Workflow"
run-name: "📊 Creating presentation: ${{ github.event.inputs.presentation_topic || 'Business Presentation' }}"

on:
  workflow_dispatch:
    inputs:
      presentation_topic:
        description: 'プレゼンテーションのテーマ・題材'
        required: true
        default: '新商品マーケティング戦略、四半期業績報告、プロジェクト提案'
        type: string
      target_audience:
        description: '対象聴衆'
        required: true
        type: choice
        options:
        - executives
        - management
        - colleagues
        - clients
        - general
        default: 'management'
      presentation_time:
        description: '発表予定時間'
        required: true
        type: choice
        options:
        - 5-minutes
        - 10-minutes
        - 15-minutes
        - 30-minutes
        - 45-minutes
        - 60-minutes
        default: '15-minutes'
      slide_count:
        description: '希望スライド数 (5-50)'
        required: true
        default: '15'
        type: choice
        options:
        - '5'
        - '10'
        - '15'
        - '20'
        - '25'
        - '30'
        - '35'
        - '40'
        - '45'
        - '50'
      content_type:
        description: 'プレゼンテーションの種類'
        required: true
        type: choice
        options:
        - proposal
        - report
        - analysis
        - training
        - sales
        - strategy
        default: 'proposal'
      data_visualization_needs:
        description: 'データ可視化の必要性'
        required: true
        type: choice
        options:
        - heavy
        - moderate
        - minimal
        default: 'moderate'
      presentation_style:
        description: 'プレゼンテーションスタイル'
        required: true
        type: choice
        options:
        - corporate
        - modern
        - creative
        - minimalist
        - technical
        default: 'corporate'
      color_preference:
        description: 'カラーテーマ（任意）'
        required: false
        type: choice
        options:
        - blue
        - green
        - red
        - purple
        - neutral
        - brand
        default: 'blue'
      purpose:
        description: 'プレゼンテーションの目的（任意）'
        required: false
        default: '新商品の承認を得る、チームの意識統一を図る、投資家への説得'
        type: string

permissions:
  contents: write
  issues: read
  actions: read

env:
  CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

jobs:
  # Phase 1: 事前テスト段階
  connectivity-test:
    runs-on: ubuntu-latest
    outputs:
      services_ready: ${{ steps.test.outputs.services_ready }}
      image_generation_available: ${{ steps.test.outputs.image_generation_available }}
    steps:
      - name: Test design and generation services
        id: test
        run: |
          echo "📊 Testing design and generation services..."
          
          mkdir -p .logs/connectivity-tests
          
          # Test Claude Code for presentation content generation
          echo "Testing presentation content generation..."
          if timeout 30 claude-code --prompt "Test: Create a simple slide title for testing." > .logs/connectivity-tests/content-test.log 2>&1; then
            CONTENT_GEN_STATUS="success"
            echo "✅ Content Generation: Available"
          else
            CONTENT_GEN_STATUS="failed"
            echo "❌ Content Generation: Failed"
          fi
          
          # Test image generation services for slide backgrounds
          echo "Testing image generation for slide backgrounds..."
          if timeout 90 claude-code --mcp-config=.claude/mcp-kamuicode.json --mcp t2i-fal-imagen4-fast --prompt "professional business presentation background, corporate style" > .logs/connectivity-tests/image-test.log 2>&1; then
            IMAGE_GEN_STATUS="success"
            echo "✅ Image Generation: Available"
          else
            IMAGE_GEN_STATUS="failed"
            echo "⚠️ Image Generation: Not available - will use text-only slides"
          fi
          
          # Set outputs
          echo "services_ready=true" >> $GITHUB_OUTPUT
          echo "image_generation_available=$IMAGE_GEN_STATUS" >> $GITHUB_OUTPUT
          
          echo "📊 Design services connectivity tests completed"

  # Phase 2: プレゼンテーション分析段階
  presentation-analysis:
    needs: connectivity-test
    runs-on: ubuntu-latest
    outputs:
      analysis_ready: ${{ steps.analyze.outputs.analysis_ready }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Analyze presentation requirements
        id: analyze
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
