name: "Social Media Content Creation Workflow"
run-name: "ðŸ“± Creating social content: ${{ github.event.inputs.content_theme || 'Social Media Campaign' }}"

on:
  workflow_dispatch:
    inputs:
      content_theme:
        description: 'ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ãƒ†ãƒ¼ãƒžãƒ»ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸'
        required: true
        default: 'æ–°å•†å“ãƒ—ãƒ­ãƒ¢ãƒ¼ã‚·ãƒ§ãƒ³ã€ãƒ–ãƒ©ãƒ³ãƒ‰èªçŸ¥å‘ä¸Šã€ã‚­ãƒ£ãƒ³ãƒšãƒ¼ãƒ³å‘ŠçŸ¥'
        type: string
      target_platforms:
        description: 'ã‚¿ãƒ¼ã‚²ãƒƒãƒˆãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ '
        required: true
        type: choice
        options:
        - multi_platform
        - instagram_focused
        - twitter_focused
        - tiktok_focused
        - linkedin_focused
        - facebook_focused
        default: 'multi_platform'
      content_style:
        description: 'ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã‚¹ã‚¿ã‚¤ãƒ«'
        required: true
        type: choice
        options:
        - casual
        - professional
        - trendy
        - educational
        - entertaining
        - minimalist
        default: 'casual'
      visual_type:
        description: 'ãƒ“ã‚¸ãƒ¥ã‚¢ãƒ«ã‚¿ã‚¤ãƒ—'
        required: true
        type: choice
        options:
        - static_image
        - carousel_images
        - short_video
        - mixed_content
        - infographic
        default: 'mixed_content'
      target_audience:
        description: 'ã‚¿ãƒ¼ã‚²ãƒƒãƒˆå±¤'
        required: true
        type: choice
        options:
        - teens
        - young_adults
        - professionals
        - families
        - seniors
        - general
        default: 'young_adults'
      posting_frequency:
        description: 'æŠ•ç¨¿é »åº¦'
        required: true
        type: choice
        options:
        - daily
        - weekly
        - campaign_burst
        - event_driven
        default: 'weekly'
      engagement_goal:
        description: 'ã‚¨ãƒ³ã‚²ãƒ¼ã‚¸ãƒ¡ãƒ³ãƒˆç›®æ¨™'
        required: true
        type: choice
        options:
        - awareness
        - engagement
        - conversion
        - community_building
        - viral_potential
        default: 'engagement'
      brand_voice:
        description: 'ãƒ–ãƒ©ãƒ³ãƒ‰ãƒœã‚¤ã‚¹'
        required: false
        type: choice
        options:
        - friendly
        - authoritative
        - playful
        - inspirational
        - informative
        - quirky
        default: 'friendly'
      call_to_action:
        description: 'ã‚³ãƒ¼ãƒ«ãƒˆã‚¥ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ï¼ˆä»»æ„ï¼‰'
        required: false
        default: 'ã„ã„ã­ãƒ»ã‚·ã‚§ã‚¢ã€ã‚³ãƒ¡ãƒ³ãƒˆæ­“è¿Žã€è©³ç´°ã¯ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«ã‹ã‚‰'
        type: string

permissions:
  contents: write
  issues: read
  actions: read

env:
  CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

jobs:
  # Phase 1: äº‹å‰ãƒ†ã‚¹ãƒˆæ®µéšŽ
  connectivity-test:
    runs-on: ubuntu-latest
    outputs:
      services_ready: ${{ steps.test.outputs.services_ready }}
      image_gen_available: ${{ steps.test.outputs.image_gen_available }}
      video_gen_available: ${{ steps.test.outputs.video_gen_available }}
    steps:
      - name: Test social media content generation services
        id: test
        run: |
          echo "ðŸ“± Testing social media content generation services..."
          
          mkdir -p .logs/connectivity-tests
          
          # ç”»åƒç”Ÿæˆã‚µãƒ¼ãƒ“ã‚¹ãƒ†ã‚¹ãƒˆï¼ˆã‚½ãƒ¼ã‚·ãƒ£ãƒ«ãƒ¡ãƒ‡ã‚£ã‚¢æŠ•ç¨¿ç”¨ï¼‰
          echo "Testing image generation for social media posts..."
          if timeout 90 claude-code --mcp-config=.claude/mcp-kamuicode.json --mcp t2i-fal-imagen4-fast --prompt "social media post image test" > .logs/connectivity-tests/image-test.log 2>&1; then
            IMAGE_GEN_STATUS="success"
            echo "âœ… Image Generation: Available"
          else
            IMAGE_GEN_STATUS="failed"
            echo "âš ï¸ Image Generation: Not available - will use text-only posts"
          fi
          
          # å‹•ç”»ç”Ÿæˆã‚µãƒ¼ãƒ“ã‚¹ãƒ†ã‚¹ãƒˆï¼ˆã‚·ãƒ§ãƒ¼ãƒˆå‹•ç”»ç”¨ï¼‰
          echo "Testing video generation for short content..."
          if timeout 120 claude-code --mcp-config=.claude/mcp-kamuicode.json --mcp t2v-fal-veo3-fast --prompt "short social media video test" > .logs/connectivity-tests/video-test.log 2>&1; then
            VIDEO_GEN_STATUS="success"
            echo "âœ… Video Generation: Available"
          else
            VIDEO_GEN_STATUS="failed"
            echo "âš ï¸ Video Generation: Not available - will focus on static content"
          fi
          
          # Set outputs
          echo "services_ready=true" >> $GITHUB_OUTPUT
          echo "image_gen_available=$IMAGE_GEN_STATUS" >> $GITHUB_OUTPUT
          echo "video_gen_available=$VIDEO_GEN_STATUS" >> $GITHUB_OUTPUT
          
          echo "ðŸ“± Social media services connectivity tests completed"

  # Phase 2: ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ åˆ†æžæ®µéšŽ
  platform-analysis:
    needs: connectivity-test
    runs-on: ubuntu-latest
    outputs:
      analysis_ready: ${{ steps.analyze.outputs.analysis_ready }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Analyze target platforms and optimization requirements
        id: analyze
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "ðŸ” Analyzing target platforms and optimization requirements..."
          
          mkdir -p .logs/platform-analysis
          
          TARGET_PLATFORMS="${{ github.event.inputs.target_platforms }}"
          CONTENT_STYLE="${{ github.event.inputs.content_style }}"
          TARGET_AUDIENCE="${{ github.event.inputs.target_audience }}"
          
          echo "Target platforms: $TARGET_PLATFORMS"
          echo "Content style: $CONTENT_STYLE"
          echo "Target audience: $TARGET_AUDIENCE"
          
          # Claude Code ã§ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ åˆ¥æœ€é©åŒ–åˆ†æž
          claude-code --prompt "ä»¥ä¸‹ã®ã‚½ãƒ¼ã‚·ãƒ£ãƒ«ãƒ¡ãƒ‡ã‚£ã‚¢è¦ä»¶ã‚’åˆ†æžã—ã€ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ åˆ¥ã®æœ€é©åŒ–æˆ¦ç•¥ã‚’JSONå½¢å¼ã§ææ¡ˆã—ã¦ãã ã•ã„ï¼š

          ã‚¿ãƒ¼ã‚²ãƒƒãƒˆãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ : $TARGET_PLATFORMS
          ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã‚¹ã‚¿ã‚¤ãƒ«: $CONTENT_STYLE
          ã‚¿ãƒ¼ã‚²ãƒƒãƒˆå±¤: $TARGET_AUDIENCE
          ãƒ“ã‚¸ãƒ¥ã‚¢ãƒ«ã‚¿ã‚¤ãƒ—: ${{ github.event.inputs.visual_type }}
          ã‚¨ãƒ³ã‚²ãƒ¼ã‚¸ãƒ¡ãƒ³ãƒˆç›®æ¨™: ${{ github.event.inputs.engagement_goal }}

          å„ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ ã®ç‰¹æ€§ã€æœ€é©ãªæŠ•ç¨¿ã‚µã‚¤ã‚ºã€ãƒãƒƒã‚·ãƒ¥ã‚¿ã‚°æˆ¦ç•¥ã€æŠ•ç¨¿æ™‚é–“ãªã©ã‚’å«ã‚ã¦ãã ã•ã„ã€‚" > .logs/platform-analysis/platform-strategy.json
          
          echo "analysis_ready=true" >> $GITHUB_OUTPUT
          echo "ðŸ” Platform analysis completed"

  # Phase 3: ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ä¼ç”»æ®µéšŽ
  content-strategy:
    needs: platform-analysis
    runs-on: ubuntu-latest
    outputs:
      strategy_ready: ${{ steps.strategy.outputs.strategy_ready }}
    steps:
      - name: Develop comprehensive content strategy
        id: strategy
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "ðŸ“‹ Developing comprehensive content strategy..."
          
          mkdir -p .logs/content-strategy
          
          CONTENT_THEME="${{ github.event.inputs.content_theme }}"
          POSTING_FREQUENCY="${{ github.event.inputs.posting_frequency }}"
          BRAND_VOICE="${{ github.event.inputs.brand_voice }}"
          
          # ã‚³ãƒ³ãƒ†ãƒ³ãƒ„æˆ¦ç•¥ã¨ã‚­ãƒ£ãƒ³ãƒšãƒ¼ãƒ³è¨­è¨ˆ
          claude-code --prompt "ä»¥ä¸‹ã®è¦ä»¶ã«åŸºã¥ã„ã¦ã€è©³ç´°ãªã‚½ãƒ¼ã‚·ãƒ£ãƒ«ãƒ¡ãƒ‡ã‚£ã‚¢ã‚³ãƒ³ãƒ†ãƒ³ãƒ„æˆ¦ç•¥ã‚’è¨­è¨ˆã—ã¦ãã ã•ã„ï¼š

          ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ãƒ†ãƒ¼ãƒž: $CONTENT_THEME
          æŠ•ç¨¿é »åº¦: $POSTING_FREQUENCY
          ãƒ–ãƒ©ãƒ³ãƒ‰ãƒœã‚¤ã‚¹: $BRAND_VOICE
          ã‚³ãƒ¼ãƒ«ãƒˆã‚¥ã‚¢ã‚¯ã‚·ãƒ§ãƒ³: ${{ github.event.inputs.call_to_action }}

          æŠ•ç¨¿ã‚«ãƒ¬ãƒ³ãƒ€ãƒ¼ã€ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã‚·ãƒªãƒ¼ã‚ºã€ã‚¨ãƒ³ã‚²ãƒ¼ã‚¸ãƒ¡ãƒ³ãƒˆæˆ¦ç•¥ã‚’JSONå½¢å¼ã§è¿”ã—ã¦ãã ã•ã„ã€‚" > .logs/content-strategy/content-plan.json
          
          echo "strategy_ready=true" >> $GITHUB_OUTPUT
          echo "ðŸ“‹ Content strategy development completed"

  # Phase 4: ãƒ“ã‚¸ãƒ¥ã‚¢ãƒ«ã‚³ãƒ³ãƒ†ãƒ³ãƒ„åˆ¶ä½œæ®µéšŽ
  visual-content-creation:
    needs: [connectivity-test, content-strategy]
    runs-on: ubuntu-latest
    outputs:
      visuals_ready: ${{ steps.create.outputs.visuals_ready }}
    steps:
      - name: Generate visual content for social media
        id: create
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "ðŸŽ¨ Generating visual content for social media..."
          
          mkdir -p .logs/visual-content
          
          IMAGE_GEN_AVAILABLE="${{ needs.connectivity-test.outputs.image_gen_available }}"
          VIDEO_GEN_AVAILABLE="${{ needs.connectivity-test.outputs.video_gen_available }}"
          VISUAL_TYPE="${{ github.event.inputs.visual_type }}"
          
          if [ "$IMAGE_GEN_AVAILABLE" = "success" ]; then
            echo "Generating social media images..."
            
            # ãƒ¡ã‚¤ãƒ³æŠ•ç¨¿ç”»åƒç”Ÿæˆ
            MAIN_IMAGE_PROMPT="${{ github.event.inputs.content_theme }}, social media post, ${{ github.event.inputs.content_style }} style, engaging visual, high quality, optimized for social platforms"
            
            claude-code --mcp-config=.claude/mcp-kamuicode.json --mcp t2i-fal-imagen4-fast --prompt "$MAIN_IMAGE_PROMPT" > .logs/visual-content/main-post-image.json 2>&1 || echo "Main image generation failed"
            
            # ã‚¤ãƒ³ã‚¹ã‚¿ã‚°ãƒ©ãƒ æ­£æ–¹å½¢ãƒ•ã‚©ãƒ¼ãƒžãƒƒãƒˆ
            SQUARE_PROMPT="${{ github.event.inputs.content_theme }}, Instagram square format, 1:1 aspect ratio, ${{ github.event.inputs.content_style }} aesthetic"
            
            claude-code --mcp-config=.claude/mcp-kamuicode.json --mcp t2i-fal-imagen4-fast --prompt "$SQUARE_PROMPT" > .logs/visual-content/instagram-square.json 2>&1 || echo "Square format generation failed"
            
            echo "âœ… Image content generated"
          else
            echo "âš ï¸ Image generation not available - will create text-only content strategy"
          fi
          
          if [ "$VIDEO_GEN_AVAILABLE" = "success" ] && [ "$VISUAL_TYPE" = "short_video" ]; then
            echo "Generating short video content..."
            
            VIDEO_PROMPT="${{ github.event.inputs.content_theme }}, short social media video, engaging, ${{ github.event.inputs.content_style }} style, 15-30 seconds"
            
            claude-code --mcp-config=.claude/mcp-kamuicode.json --mcp t2v-fal-veo3-fast --prompt "$VIDEO_PROMPT" > .logs/visual-content/short-video.json 2>&1 || echo "Video generation failed"
            
            echo "âœ… Video content generated"
          else
            echo "â„¹ï¸ Video generation skipped or not available"
          fi
          
          echo "visuals_ready=true" >> $GITHUB_OUTPUT
          echo "ðŸŽ¨ Visual content creation completed"

  # Phase 5: ãƒ†ã‚­ã‚¹ãƒˆæœ€é©åŒ–æ®µéšŽ
  text-optimization:
    needs: content-strategy
    runs-on: ubuntu-latest
    outputs:
      text_ready: ${{ steps.optimize.outputs.text_ready }}
    steps:
      - name: Generate and optimize platform-specific text content
        id: optimize
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "ðŸ“ Generating and optimizing platform-specific text content..."
          
          mkdir -p .logs/text-optimization
          
          TARGET_PLATFORMS="${{ github.event.inputs.target_platforms }}"
          CONTENT_THEME="${{ github.event.inputs.content_theme }}"
          BRAND_VOICE="${{ github.event.inputs.brand_voice }}"
          
          # ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ åˆ¥ãƒ†ã‚­ã‚¹ãƒˆæœ€é©åŒ–
          claude-code --prompt "ä»¥ä¸‹ã®è¦ä»¶ã«åŸºã¥ã„ã¦ã€å„ã‚½ãƒ¼ã‚·ãƒ£ãƒ«ãƒ¡ãƒ‡ã‚£ã‚¢ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ å‘ã‘ã«æœ€é©åŒ–ã•ã‚ŒãŸãƒ†ã‚­ã‚¹ãƒˆã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã‚’ä½œæˆã—ã¦ãã ã•ã„ï¼š

          ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ãƒ†ãƒ¼ãƒž: $CONTENT_THEME
          å¯¾è±¡ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ : $TARGET_PLATFORMS
          ãƒ–ãƒ©ãƒ³ãƒ‰ãƒœã‚¤ã‚¹: $BRAND_VOICE
          ã‚³ãƒ¼ãƒ«ãƒˆã‚¥ã‚¢ã‚¯ã‚·ãƒ§ãƒ³: ${{ github.event.inputs.call_to_action }}

          ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ åˆ¥ã®æ–‡å­—æ•°åˆ¶é™ã€ãƒãƒƒã‚·ãƒ¥ã‚¿ã‚°æˆ¦ç•¥ã€ã‚¨ãƒ³ã‚²ãƒ¼ã‚¸ãƒ¡ãƒ³ãƒˆæœ€é©åŒ–ã‚’è€ƒæ…®ã—ã¦JSONå½¢å¼ã§è¿”ã—ã¦ãã ã•ã„ã€‚" > .logs/text-optimization/platform-text.json
          
          echo "text_ready=true" >> $GITHUB_OUTPUT
          echo "ðŸ“ Text optimization completed"

  # Phase 6: ãƒãƒƒã‚·ãƒ¥ã‚¿ã‚°ãƒ»SEOæœ€é©åŒ–æ®µéšŽ
  hashtag-seo-optimization:
    needs: text-optimization
    runs-on: ubuntu-latest
    outputs:
      seo_ready: ${{ steps.seo.outputs.seo_ready }}
    steps:
      - name: Generate hashtag strategy and SEO optimization
        id: seo
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "ðŸ” Generating hashtag strategy and SEO optimization..."
          
          mkdir -p .logs/hashtag-seo
          
          # ãƒãƒƒã‚·ãƒ¥ã‚¿ã‚°æˆ¦ç•¥ã¨SEOæœ€é©åŒ–
          claude-code --prompt "ä»¥ä¸‹ã®ã‚½ãƒ¼ã‚·ãƒ£ãƒ«ãƒ¡ãƒ‡ã‚£ã‚¢ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã«å¯¾ã—ã¦ã€ãƒãƒƒã‚·ãƒ¥ã‚¿ã‚°æˆ¦ç•¥ã¨SEOæœ€é©åŒ–ã‚’è¨­è¨ˆã—ã¦ãã ã•ã„ï¼š

          ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ãƒ†ãƒ¼ãƒž: ${{ github.event.inputs.content_theme }}
          ã‚¿ãƒ¼ã‚²ãƒƒãƒˆå±¤: ${{ github.event.inputs.target_audience }}
          ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ : ${{ github.event.inputs.target_platforms }}
          ã‚¨ãƒ³ã‚²ãƒ¼ã‚¸ãƒ¡ãƒ³ãƒˆç›®æ¨™: ${{ github.event.inputs.engagement_goal }}

          äººæ°—ãƒãƒƒã‚·ãƒ¥ã‚¿ã‚°ã€ãƒ‹ãƒƒãƒãƒãƒƒã‚·ãƒ¥ã‚¿ã‚°ã€ãƒ–ãƒ©ãƒ³ãƒ‰ãƒãƒƒã‚·ãƒ¥ã‚¿ã‚°ã®çµ„ã¿åˆã‚ã›æˆ¦ç•¥ã‚’JSONå½¢å¼ã§è¿”ã—ã¦ãã ã•ã„ã€‚" > .logs/hashtag-seo/hashtag-strategy.json
          
          echo "seo_ready=true" >> $GITHUB_OUTPUT
          echo "ðŸ” Hashtag and SEO optimization completed"

  # Phase 7: æœ€çµ‚ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ä½œæˆ
  final-packaging:
    needs: [platform-analysis, content-strategy, visual-content-creation, text-optimization, hashtag-seo-optimization]
    runs-on: ubuntu-latest
    steps:
      - name: Create comprehensive social media campaign package
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "ðŸ“¦ Creating comprehensive social media campaign package..."
          
          mkdir -p .final-output/{strategy,content,visuals,optimization}
          
          # æˆ¦ç•¥ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
          cp .logs/platform-analysis/platform-strategy.json .final-output/strategy/ 2>/dev/null || true
          cp .logs/content-strategy/content-plan.json .final-output/strategy/ 2>/dev/null || true
          
          # ãƒ“ã‚¸ãƒ¥ã‚¢ãƒ«ã‚³ãƒ³ãƒ†ãƒ³ãƒ„
          cp .logs/visual-content/*.json .final-output/visuals/ 2>/dev/null || true
          
          # ãƒ†ã‚­ã‚¹ãƒˆãƒ»æœ€é©åŒ–è³‡æ–™
          cp .logs/text-optimization/platform-text.json .final-output/content/ 2>/dev/null || true
          cp .logs/hashtag-seo/hashtag-strategy.json .final-output/optimization/ 2>/dev/null || true
          
          # ãƒžã‚¹ã‚¿ãƒ¼ã‚½ãƒ¼ã‚·ãƒ£ãƒ«ãƒ¡ãƒ‡ã‚£ã‚¢æƒ…å ±
          cat > .final-output/social-media-master.json << EOF
          {
            "project_info": {
              "project_name": "Social Media Content Creation",
              "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
              "github_run_id": "${{ github.run_id }}",
              "campaign_type": "social_media_content_generation"
            },
            "input_parameters": {
              "content_theme": "${{ github.event.inputs.content_theme }}",
              "target_platforms": "${{ github.event.inputs.target_platforms }}",
              "content_style": "${{ github.event.inputs.content_style }}",
              "visual_type": "${{ github.event.inputs.visual_type }}",
              "target_audience": "${{ github.event.inputs.target_audience }}",
              "posting_frequency": "${{ github.event.inputs.posting_frequency }}",
              "engagement_goal": "${{ github.event.inputs.engagement_goal }}",
              "brand_voice": "${{ github.event.inputs.brand_voice }}",
              "call_to_action": "${{ github.event.inputs.call_to_action }}"
            },
            "deliverables": {
              "strategy_documents": {
                "platform_strategy": "strategy/platform-strategy.json",
                "content_plan": "strategy/content-plan.json"
              },
              "visual_content": {
                "generated_visuals": "visuals/"
              },
              "text_content": {
                "platform_optimized_text": "content/platform-text.json"
              },
              "optimization": {
                "hashtag_strategy": "optimization/hashtag-strategy.json"
              }
            }
          }
          EOF
          
          # ã‚½ãƒ¼ã‚·ãƒ£ãƒ«ãƒ¡ãƒ‡ã‚£ã‚¢ã‚­ãƒ£ãƒ³ãƒšãƒ¼ãƒ³ã‚¬ã‚¤ãƒ‰
          cat > .final-output/SOCIAL_MEDIA_GUIDE.md << 'EOF'
          # ã‚½ãƒ¼ã‚·ãƒ£ãƒ«ãƒ¡ãƒ‡ã‚£ã‚¢ã‚³ãƒ³ãƒ†ãƒ³ãƒ„åˆ¶ä½œã‚¬ã‚¤ãƒ‰
          
          ## ðŸ“± ã‚­ãƒ£ãƒ³ãƒšãƒ¼ãƒ³æ¦‚è¦
          - åˆ¶ä½œæ‰‹æ³•: AIç”Ÿæˆã«ã‚ˆã‚‹çµ±åˆã‚½ãƒ¼ã‚·ãƒ£ãƒ«ãƒ¡ãƒ‡ã‚£ã‚¢ã‚³ãƒ³ãƒ†ãƒ³ãƒ„
          - å“è³ªãƒ¬ãƒ™ãƒ«: ãƒ—ãƒ­ãƒ•ã‚§ãƒƒã‚·ãƒ§ãƒŠãƒ«ãƒžãƒ¼ã‚±ãƒ†ã‚£ãƒ³ã‚°å¯¾å¿œ
          - æœ€é©åŒ–: ãƒžãƒ«ãƒãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ æˆ¦ç•¥
          
          ## ðŸŽ¯ æˆ¦ç•¥è¨­è¨ˆ
          - ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ åˆ¥ç‰¹æ€§åˆ†æž
          - ã‚¿ãƒ¼ã‚²ãƒƒãƒˆå±¤ãƒžãƒƒãƒ”ãƒ³ã‚°
          - ã‚¨ãƒ³ã‚²ãƒ¼ã‚¸ãƒ¡ãƒ³ãƒˆæˆ¦ç•¥
          - æŠ•ç¨¿ã‚«ãƒ¬ãƒ³ãƒ€ãƒ¼æœ€é©åŒ–
          
          ## ðŸŽ¨ ã‚³ãƒ³ãƒ†ãƒ³ãƒ„åˆ¶ä½œ
          - ãƒ“ã‚¸ãƒ¥ã‚¢ãƒ«ã‚¢ã‚»ãƒƒãƒˆç”Ÿæˆ
          - ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ åˆ¥ã‚µã‚¤ã‚ºæœ€é©åŒ–
          - ãƒ–ãƒ©ãƒ³ãƒ‰çµ±ä¸€æ€§ç¢ºä¿
          - å‹•ç”»ãƒ»é™æ­¢ç”»ã‚³ãƒ³ãƒ†ãƒ³ãƒ„
          
          ## ðŸ“ ãƒ†ã‚­ã‚¹ãƒˆæœ€é©åŒ–
          - ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ åˆ¥æ–‡å­—æ•°èª¿æ•´
          - ãƒ–ãƒ©ãƒ³ãƒ‰ãƒœã‚¤ã‚¹çµ±ä¸€
          - ã‚³ãƒ¼ãƒ«ãƒˆã‚¥ã‚¢ã‚¯ã‚·ãƒ§ãƒ³è¨­è¨ˆ
          - ãƒãƒƒã‚·ãƒ¥ã‚¿ã‚°æˆ¦ç•¥å®Ÿè£…
          
          ## ðŸ“Š ãƒ‘ãƒ•ã‚©ãƒ¼ãƒžãƒ³ã‚¹æœ€é©åŒ–
          - ã‚¨ãƒ³ã‚²ãƒ¼ã‚¸ãƒ¡ãƒ³ãƒˆæœ€å¤§åŒ–
          - ãƒªãƒ¼ãƒæ‹¡å¤§æˆ¦ç•¥
          - ã‚³ãƒ³ãƒãƒ¼ã‚¸ãƒ§ãƒ³èª˜å°Ž
          - åˆ†æžãƒ»æ”¹å–„ã‚µã‚¤ã‚¯ãƒ«
          EOF
          
          echo "ðŸ“¦ Final social media campaign packaging completed"
          
      - name: Upload Social Media Campaign Package
        uses: actions/upload-artifact@v4
        with:
          name: social-media-campaign-${{ github.run_number }}
          path: .final-output/
          retention-days: 30