name: local-save
description: å…¨ã‚¢ãƒ¼ãƒ†ã‚£ãƒ•ã‚¡ã‚¯ãƒˆã®æ•´ç†ã•ã‚ŒãŸä¿å­˜ã¨Gitç®¡ç†

on:
  workflow_call:
    inputs:
      project_concept:
        description: 'ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã‚³ãƒ³ã‚»ãƒ—ãƒˆï¼ˆãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªåã«ä½¿ç”¨ï¼‰'
        required: true
        type: string
      artifact_pattern:
        description: 'ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰ã™ã‚‹ã‚¢ãƒ¼ãƒ†ã‚£ãƒ•ã‚¡ã‚¯ãƒˆã®ãƒ‘ã‚¿ãƒ¼ãƒ³'
        required: false
        type: string
        default: '*-${{ github.run_number }}'
      dir_prefix:
        description: 'ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªåã®ãƒ—ãƒ¬ãƒ•ã‚£ãƒƒã‚¯ã‚¹'
        required: false
        type: string
        default: 'video-v8-run'
      organize_structure:
        description: 'æ•´ç†ã•ã‚ŒãŸæ§‹é€ ã§ä¿å­˜ã™ã‚‹ã‹'
        required: false
        type: boolean
        default: true
      workflow_name:
        description: 'ãƒ¯ãƒ¼ã‚¯ãƒ•ãƒ­ãƒ¼åï¼ˆãƒ¡ã‚¿ãƒ‡ãƒ¼ã‚¿ç”¨ï¼‰'
        required: false
        type: string
        default: 'workflow'
    outputs:
      saved_path:
        description: 'ä¿å­˜ã•ã‚ŒãŸãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã®ãƒ‘ã‚¹'
        value: ${{ jobs.save.outputs.saved_path }}
      project_dir:
        description: 'ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªå'
        value: ${{ jobs.save.outputs.project_dir }}

jobs:
  save:
    runs-on: ubuntu-latest
    outputs:
      saved_path: ${{ steps.save-all.outputs.saved_path }}
      project_dir: ${{ steps.save-all.outputs.project_dir }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.artifact_pattern }}
          path: temp-all-artifacts/
          
      - name: Save All Outputs to Projects
        id: save-all
        run: |
          echo "ðŸ’¾ Saving all outputs to projects directory..."
          
          # ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆåã®ç”Ÿæˆï¼ˆç‰¹æ®Šæ–‡å­—ã‚’å‡¦ç†ï¼‰
          PROJECT_NAME=$(echo "${{ inputs.project_concept }}" | sed 's/[^a-zA-Z0-9-]/-/g' | sed 's/--*/-/g' | cut -c1-50)
          PROJECT_DIR="${{ inputs.dir_prefix }}-${{ github.run_number }}-${PROJECT_NAME}"
          
          # ãƒ¡ã‚¤ãƒ³ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªä½œæˆ
          mkdir -p "projects/$PROJECT_DIR"
          
          if [ "${{ inputs.organize_structure }}" == "true" ]; then
            echo "ðŸ“‚ Organizing artifacts with structured layout..."
            
            # æœ€çµ‚æˆæžœç‰©
            if [ -d "temp-all-artifacts/final-video-package-${{ github.run_number }}" ]; then
              cp -r "temp-all-artifacts/final-video-package-${{ github.run_number }}"/* "projects/$PROJECT_DIR/"
            fi
            
            # ä¼ç”»ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
            if [ -d "temp-all-artifacts/planning-${{ github.run_number }}" ]; then
              mkdir -p "projects/$PROJECT_DIR/planning"
              cp -r "temp-all-artifacts/planning-${{ github.run_number }}"/* "projects/$PROJECT_DIR/planning/"
            fi
            
            # ç”Ÿæˆç”»åƒï¼ˆã‚·ãƒ¼ãƒ³ã”ã¨ï¼‰
            for scene in intro main outro; do
              if [ -d "temp-all-artifacts/images-${scene}-${{ github.run_number }}" ]; then
                mkdir -p "projects/$PROJECT_DIR/images/${scene}"
                cp -r "temp-all-artifacts/images-${scene}-${{ github.run_number }}"/* "projects/$PROJECT_DIR/images/${scene}/"
              fi
            done
            
            # ç”Ÿæˆå‹•ç”»ï¼ˆã‚·ãƒ¼ãƒ³ã”ã¨ï¼‰
            for scene in intro main outro; do
              if [ -d "temp-all-artifacts/videos-${scene}-${{ github.run_number }}" ]; then
                mkdir -p "projects/$PROJECT_DIR/videos/${scene}"
                cp -r "temp-all-artifacts/videos-${scene}-${{ github.run_number }}"/* "projects/$PROJECT_DIR/videos/${scene}/"
              fi
            done
            
            # BGM
            if [ -d "temp-all-artifacts/bgm-${{ github.run_number }}" ]; then
              mkdir -p "projects/$PROJECT_DIR/audio/bgm"
              cp -r "temp-all-artifacts/bgm-${{ github.run_number }}"/* "projects/$PROJECT_DIR/audio/bgm/"
            fi
            
            # ãƒŠãƒ¬ãƒ¼ã‚·ãƒ§ãƒ³
            if [ -d "temp-all-artifacts/narration-${{ github.run_number }}" ]; then
              mkdir -p "projects/$PROJECT_DIR/audio/narration"
              cp -r "temp-all-artifacts/narration-${{ github.run_number }}"/* "projects/$PROJECT_DIR/audio/narration/"
            fi
            
            # ç’°å¢ƒæƒ…å ±
            if [ -d "temp-all-artifacts/environment-${{ github.run_number }}" ]; then
              mkdir -p "projects/$PROJECT_DIR/metadata"
              cp -r "temp-all-artifacts/environment-${{ github.run_number }}"/* "projects/$PROJECT_DIR/metadata/"
            fi
          else
            # ãƒ•ãƒ©ãƒƒãƒˆãªæ§‹é€ ã§ä¿å­˜
            echo "ðŸ“‚ Saving artifacts with flat structure..."
            cp -r temp-all-artifacts/* "projects/$PROJECT_DIR/"
          fi
          
          # ãƒ¯ãƒ¼ã‚¯ãƒ•ãƒ­ãƒ¼ãƒ¡ã‚¿ãƒ‡ãƒ¼ã‚¿ä½œæˆ
          cat > "projects/$PROJECT_DIR/workflow-info.json" << EOF
          {
            "workflow": "${{ inputs.workflow_name }}",
            "run_number": ${{ github.run_number }},
            "run_id": "${{ github.run_id }}",
            "concept": "${{ inputs.project_concept }}",
            "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "github_actor": "${{ github.actor }}",
            "github_ref": "${{ github.ref }}",
            "organized": ${{ inputs.organize_structure }},
            "structure": {
              "planning": "ä¼ç”»ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ",
              "images": "ç”Ÿæˆç”»åƒï¼ˆintro/main/outroï¼‰",
              "videos": "ç”Ÿæˆå‹•ç”»ï¼ˆintro/main/outroï¼‰", 
              "audio": {
                "bgm": "èƒŒæ™¯éŸ³æ¥½",
                "narration": "ãƒŠãƒ¬ãƒ¼ã‚·ãƒ§ãƒ³éŸ³å£°"
              },
              "metadata": "ç’°å¢ƒæƒ…å ±ãƒ»å®Ÿè¡Œãƒ­ã‚°"
            }
          }
          EOF
          
          echo "saved_path=projects/$PROJECT_DIR" >> $GITHUB_OUTPUT
          echo "project_dir=$PROJECT_DIR" >> $GITHUB_OUTPUT
          echo "âœ… Saved to: projects/$PROJECT_DIR"
          
          # ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªæ§‹é€ ã‚’è¡¨ç¤º
          echo "ðŸ“ Project structure:"
          tree "projects/$PROJECT_DIR/" -L 3 2>/dev/null || find "projects/$PROJECT_DIR/" -type d | sort
          
      - name: Cleanup
        if: always()
        run: |
          rm -rf temp-all-artifacts/