# ⚠️ 重要：これは参照テンプレートです。実際のワークフローではインライン実装してください
# 詳細は /minimal-units/USAGE_GUIDELINES.md を参照

name: t2v-veo3
description: FAL Veo3テキストから動画生成の最小単位ユニット（MCP統合版）

on:
  workflow_call:
    inputs:
      prompt:
        description: '動画生成プロンプト'
        required: true
        type: string
      output_dir:
        description: '出力ディレクトリパス'
        required: true
        type: string
      duration:
        description: '動画の長さ（秒）'
        required: false
        type: string
        default: '5'
      aspect_ratio:
        description: 'アスペクト比'
        required: false
        type: string
        default: '16:9'
      quality:
        description: '品質設定（draft/standard/high）'
        required: false
        type: string
        default: 'standard'
    outputs:
      video_path:
        description: '生成された動画パス'
        value: ${{ jobs.generate.outputs.video_path }}
      video_url:
        description: '動画URL'
        value: ${{ jobs.generate.outputs.video_url }}
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN:
        description: 'Claude Code OAuth Token'
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      video_path: ${{ steps.execute.outputs.video_path }}
      video_url: ${{ steps.execute.outputs.video_url }}
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Claude Code
        run: |
          npm init -y
          npm install @anthropic-ai/claude-code
      
      - name: Generate Video with Veo3
        id: execute
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          CLAUDE_CODE_CI_MODE: true
          CLAUDE_CODE_AUTO_APPROVE_MCP: true
        run: |
          # ディレクトリ作成
          mkdir -p "${{ inputs.output_dir }}"
          
          # Claude Code CLIでMCP経由で動画生成
          CLAUDE_PROMPT="Generate a video using t2v-fal-veo3-fast with the following requirements:
          
          **Prompt**: ${{ inputs.prompt }}
          **Duration**: ${{ inputs.duration }}s
          **Aspect Ratio**: ${{ inputs.aspect_ratio }}
          **Auto Open**: false
          **Output Directory**: ${{ inputs.output_dir }}
          
          Steps:
          1. Use mcp__t2v-kamui-veo3-fast__veo3_fast_submit to submit the video generation request
          2. Save the request_id to a file
          3. Use mcp__t2v-kamui-veo3-fast__veo3_fast_status to check the status (may take 30-60 seconds)
          4. When completed, use mcp__t2v-kamui-veo3-fast__veo3_fast_result to download the video
          5. List the downloaded files and rename the first .mp4 file to video.mp4
          6. Save the video URL to video-url.txt
          
          Important: Make sure to wait for the generation to complete before downloading."
          
          npx @anthropic-ai/claude-code \
            -p "$CLAUDE_PROMPT" \
            --mcp-config ".claude/mcp-kamuicode.json" \
            --allowedTools "mcp__t2v-kamui-veo3-fast__veo3_fast_submit,mcp__t2v-kamui-veo3-fast__veo3_fast_status,mcp__t2v-kamui-veo3-fast__veo3_fast_result,Bash,Write" \
            --permission-mode "acceptEdits"
          
          # 結果確認とファイル名の柔軟な処理
          cd "${{ inputs.output_dir }}"
          
          # video.mp4が存在しない場合の自動修正
          if [ ! -f "video.mp4" ]; then
            for file in *.mp4; do
              if [ -f "$file" ] && [ "$file" != "video.mp4" ]; then
                mv "$file" "video.mp4"
                echo "✅ Renamed $file to video.mp4"
                break
              fi
            done
          fi
          
          # URLファイルを確認
          if [ -f "video-url.txt" ]; then
            VIDEO_URL=$(cat video-url.txt)
          else
            VIDEO_URL="generated-video-url"
          fi
          
          # 最終確認
          if [ -f "video.mp4" ]; then
            echo "video_path=${{ inputs.output_dir }}/video.mp4" >> $GITHUB_OUTPUT
            echo "video_url=$VIDEO_URL" >> $GITHUB_OUTPUT
            echo "✅ Video generation completed successfully"
          else
            echo "❌ Video generation failed - no video file found"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi