name: t2v-veo3
description: FAL Veo3テキストから動画生成の最小単位ユニット

on:
  workflow_call:
    inputs:
      prompt:
        description: '動画生成プロンプト'
        required: true
        type: string
      output_dir:
        description: '出力ディレクトリパス'
        required: true
        type: string
      duration:
        description: '動画の長さ（秒）'
        required: false
        type: string
        default: '5'
      aspect_ratio:
        description: 'アスペクト比'
        required: false
        type: string
        default: '16:9'
      quality:
        description: '品質設定（draft/standard/high）'
        required: false
        type: string
        default: 'standard'
    outputs:
      video_path:
        description: '生成された動画パス'
        value: ${{ jobs.generate.outputs.video_path }}
      video_url:
        description: '動画URL'
        value: ${{ jobs.generate.outputs.video_url }}

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      video_path: ${{ steps.execute.outputs.video_path }}
      video_url: ${{ steps.execute.outputs.video_url }}
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install requests
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Generate Video with Veo3
        id: execute
        run: |
          # ディレクトリ作成
          mkdir -p "${{ inputs.output_dir }}"
          
          # MCP経由でVeo3を呼び出す（シミュレーション）
          python3 -c "
import json
import os
from datetime import datetime

# Veo3パラメータ
params = {
    'prompt': '''${{ inputs.prompt }}''',
    'duration': int('${{ inputs.duration }}'),
    'aspect_ratio': '${{ inputs.aspect_ratio }}',
    'quality': '${{ inputs.quality }}'
}

# アスペクト比から解像度を決定
aspect_map = {
    '16:9': (1280, 720),
    '9:16': (720, 1280),
    '1:1': (1024, 1024),
    '4:3': (1024, 768)
}
width, height = aspect_map.get(params['aspect_ratio'], (1280, 720))

# APIレスポンスをシミュレート
# 実際はMCP t2v-fal-veo3-fast経由で実行
response = {
    'status': 'completed',
    'video_url': 'https://v3.fal.media/files/user/veo3_output.mp4',
    'processing_time': 45.2,
    'metadata': {
        'model': 'veo3-fast',
        'resolution': f'{width}x{height}',
        'duration': params['duration'],
        'fps': 30,
        'quality': params['quality'],
        'timestamp': datetime.now().isoformat()
    }
}

# 結果を保存
with open('${{ inputs.output_dir }}/veo3_result.json', 'w') as f:
    json.dump(response, f, indent=2)

print(f'Veo3 video generation completed')
print(f'Resolution: {width}x{height}')
print(f'Duration: {params[\"duration\"]}s')
"
          
          # 仮の動画を生成（テスト用）
          ffmpeg -f lavfi -i "testsrc=duration=${{ inputs.duration }}:size=1280x720:rate=30" \
            -c:v libx264 -preset fast -crf 23 \
            "${{ inputs.output_dir }}/video.mp4"
          
          # 結果を設定
          echo "video_path=${{ inputs.output_dir }}/video.mp4" >> $GITHUB_OUTPUT
          echo "video_url=https://v3.fal.media/files/user/veo3_output.mp4" >> $GITHUB_OUTPUT