name: video-prompt-opt
description: 動画プロンプト最適化の最小単位ユニット

on:
  workflow_call:
    inputs:
      content_type:
        description: 'コンテンツタイプ（video, animation, motion graphic, etc.）'
        required: false
        type: string
        default: 'video'
      concept:
        description: 'ユーザーのコンセプト'
        required: true
        type: string
      video_concept:
        description: '動画コンセプト'
        required: true
        type: string
      image_path:
        description: '参照画像パス'
        required: true
        type: string
      output_dir:
        description: '出力ディレクトリパス'
        required: true
        type: string
    outputs:
      optimized_prompt:
        description: '最適化された動画プロンプト'
        value: ${{ jobs.optimize.outputs.optimized_prompt }}
      analysis_path:
        description: '分析レポートパス'
        value: ${{ jobs.optimize.outputs.analysis_path }}
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN:
        description: 'Anthropic API Key'
        required: true

jobs:
  optimize:
    runs-on: ubuntu-latest
    outputs:
      optimized_prompt: ${{ steps.execute.outputs.optimized_prompt }}
      analysis_path: ${{ steps.execute.outputs.analysis_path }}
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Claude Code SDK
        run: npm install @anthropic-ai/claude-code
      
      - name: Optimize Video Prompt
        id: execute
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          # ディレクトリ作成
          mkdir -p "${{ inputs.output_dir }}"
          
          # プロンプトの構築
          CONTENT_TYPE="${{ inputs.content_type }}"
          
          PROMPT="You are a ${CONTENT_TYPE} generation expert. Analyze the image and create an optimized prompt for ${CONTENT_TYPE} generation.

          **User Concept**: ${{ inputs.concept }}
          **${CONTENT_TYPE} Concept**: ${{ inputs.video_concept }}
          **Reference Image**: ${{ inputs.image_path }}

          Tasks:
          1. Analyze the image content in detail
          2. Identify visual elements (colors, composition, objects, style)
          3. Create an optimized ${CONTENT_TYPE} generation prompt (30-80 words)
          4. Save the prompt to '${{ inputs.output_dir }}/${CONTENT_TYPE}-prompt.txt'
          5. Save analysis to '${{ inputs.output_dir }}/analysis.md'

          Focus on:
          - Specific motion based on image content
          - Natural and appealing storytelling
          - Technical constraints consideration
          - Time-based motion instructions"
          
          # Claude Code実行
          npx @anthropic-ai/claude-code \
            --allowedTools "Read,Write" \
            --max-turns 10 \
            --permission-mode "acceptEdits" \
            -p "$PROMPT"
          
          # 結果確認
          OUTPUT_FILE="${{ inputs.output_dir }}/${CONTENT_TYPE}-prompt.txt"
          if [ -f "$OUTPUT_FILE" ]; then
            OPTIMIZED_PROMPT=$(cat "$OUTPUT_FILE" | tr '\n' ' ')
            echo "optimized_prompt=$OPTIMIZED_PROMPT" >> $GITHUB_OUTPUT
            echo "analysis_path=${{ inputs.output_dir }}/analysis.md" >> $GITHUB_OUTPUT
          else
            echo "❌ Optimization failed"
            exit 1
          fi