name: video-concat
description: å‹•ç”»çµåˆã®æœ€å°å˜ä½ãƒ¦ãƒ‹ãƒƒãƒˆ

on:
  workflow_call:
    inputs:
      video_list:
        description: 'çµåˆã™ã‚‹å‹•ç”»ãƒ•ã‚¡ã‚¤ãƒ«ã®ãƒªã‚¹ãƒˆï¼ˆã‚«ãƒ³ãƒžåŒºåˆ‡ã‚Šï¼‰'
        required: true
        type: string
      output_dir:
        description: 'å‡ºåŠ›ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªãƒ‘ã‚¹'
        required: true
        type: string
      audio_path:
        description: 'BGMéŸ³å£°ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‘ã‚¹ï¼ˆã‚ªãƒ—ã‚·ãƒ§ãƒ³ï¼‰'
        required: false
        type: string
      narration_path:
        description: 'ãƒŠãƒ¬ãƒ¼ã‚·ãƒ§ãƒ³éŸ³å£°ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‘ã‚¹ï¼ˆã‚ªãƒ—ã‚·ãƒ§ãƒ³ï¼‰'
        required: false
        type: string
      transition:
        description: 'ãƒˆãƒ©ãƒ³ã‚¸ã‚·ãƒ§ãƒ³åŠ¹æžœ'
        required: false
        type: string
        default: 'none'
    outputs:
      video_path:
        description: 'çµåˆã•ã‚ŒãŸå‹•ç”»ã®ãƒ‘ã‚¹'
        value: ${{ jobs.concat.outputs.video_path }}
      duration:
        description: 'å‹•ç”»ã®é•·ã•ï¼ˆç§’ï¼‰'
        value: ${{ jobs.concat.outputs.duration }}

jobs:
  concat:
    runs-on: ubuntu-latest
    outputs:
      video_path: ${{ steps.execute.outputs.video_path }}
      duration: ${{ steps.execute.outputs.duration }}
    
    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Concatenate Videos
        id: execute
        run: |
          # ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªä½œæˆ
          mkdir -p "${{ inputs.output_dir }}"
          
          # å‹•ç”»ãƒªã‚¹ãƒˆã‚’ãƒ•ã‚¡ã‚¤ãƒ«ã«æ›¸ãè¾¼ã¿
          echo "# Video concat list" > "${{ inputs.output_dir }}/concat_list.txt"
          IFS=',' read -ra VIDEO_ARRAY <<< "${{ inputs.video_list }}"
          for video in "${VIDEO_ARRAY[@]}"; do
            echo "file '$video'" >> "${{ inputs.output_dir }}/concat_list.txt"
          done
          
          # å‹•ç”»ã‚’çµåˆ
          if [ "${{ inputs.transition }}" = "none" ]; then
            # ã‚·ãƒ³ãƒ—ãƒ«ãªçµåˆ
            ffmpeg -f concat -safe 0 -i "${{ inputs.output_dir }}/concat_list.txt" \
              -c copy -y "${{ inputs.output_dir }}/concat_temp.mp4"
          else
            # ãƒˆãƒ©ãƒ³ã‚¸ã‚·ãƒ§ãƒ³ä»˜ãçµåˆï¼ˆè¤‡é›‘ãªå‡¦ç†ã®ãŸã‚ç°¡æ˜“ç‰ˆï¼‰
            ffmpeg -f concat -safe 0 -i "${{ inputs.output_dir }}/concat_list.txt" \
              -c:v libx264 -preset fast -crf 23 \
              -c:a aac -b:a 192k \
              -y "${{ inputs.output_dir }}/concat_temp.mp4"
          fi
          
          # éŸ³å£°ãƒˆãƒ©ãƒƒã‚¯å‡¦ç†ï¼ˆv8ãƒ¯ãƒ¼ã‚¯ãƒ•ãƒ­ãƒ¼ã‹ã‚‰ï¼‰
          HAS_BGM=false
          HAS_NARRATION=false
          
          if [ -n "${{ inputs.audio_path }}" ] && [ -f "${{ inputs.audio_path }}" ]; then
            HAS_BGM=true
          fi
          
          if [ -n "${{ inputs.narration_path }}" ] && [ -f "${{ inputs.narration_path }}" ]; then
            # ãƒŠãƒ¬ãƒ¼ã‚·ãƒ§ãƒ³ãƒ•ã‚¡ã‚¤ãƒ«ã®æœ‰åŠ¹æ€§ã‚’ãƒã‚§ãƒƒã‚¯
            FILE_TYPE=$(file -b "${{ inputs.narration_path }}" | cut -d' ' -f1)
            FILE_SIZE=$(stat -c%s "${{ inputs.narration_path }}" 2>/dev/null || echo "0")
            if [[ "$FILE_TYPE" == "Audio" ]] || [[ "$FILE_TYPE" == "ISO" ]] || [[ "$FILE_TYPE" == "MPEG" ]] || [ "$FILE_SIZE" -gt 1000 ]; then
              HAS_NARRATION=true
            fi
          fi
          
          # éŸ³å£°çµ„ã¿åˆã‚ã›ãƒ­ã‚¸ãƒƒã‚¯
          if [ "$HAS_BGM" = true ] && [ "$HAS_NARRATION" = true ]; then
            echo "ðŸŽµ Adding both BGM and narration..."
            ffmpeg -i "${{ inputs.output_dir }}/concat_temp.mp4" \
              -i "${{ inputs.audio_path }}" \
              -i "${{ inputs.narration_path }}" \
              -filter_complex "[1:a]volume=0.3[bgm];[2:a]volume=1.0[narration];[bgm][narration]amix=inputs=2:duration=longest[audio]" \
              -map 0:v -map "[audio]" \
              -c:v copy -c:a aac -b:a 192k \
              -y "${{ inputs.output_dir }}/final_video.mp4"
          elif [ "$HAS_BGM" = true ]; then
            echo "ðŸŽµ Adding BGM only..."
            ffmpeg -i "${{ inputs.output_dir }}/concat_temp.mp4" \
              -i "${{ inputs.audio_path }}" \
              -filter_complex "[1:a]volume=0.3[bgm]" \
              -map 0:v -map "[bgm]" \
              -c:v copy -c:a aac -b:a 192k \
              -y "${{ inputs.output_dir }}/final_video.mp4"
          elif [ "$HAS_NARRATION" = true ]; then
            echo "ðŸŽ¤ Adding narration only..."
            ffmpeg -i "${{ inputs.output_dir }}/concat_temp.mp4" \
              -i "${{ inputs.narration_path }}" \
              -map 0:v -map 1:a \
              -c:v copy -c:a aac -b:a 192k \
              -y "${{ inputs.output_dir }}/final_video.mp4"
          else
            echo "âš ï¸ No audio tracks to add"
            mv "${{ inputs.output_dir }}/concat_temp.mp4" "${{ inputs.output_dir }}/final_video.mp4"
          fi
          
          # å‹•ç”»ã®é•·ã•ã‚’å–å¾—
          DURATION=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${{ inputs.output_dir }}/final_video.mp4")
          
          # å‡ºåŠ›è¨­å®š
          echo "video_path=${{ inputs.output_dir }}/final_video.mp4" >> $GITHUB_OUTPUT
          echo "duration=$DURATION" >> $GITHUB_OUTPUT