name: t2s-minimax-turbo-mcp
description: MiniMax Speech-02 TurboéŸ³å£°ç”Ÿæˆã®æœ€å°å˜ä½ãƒ¦ãƒ‹ãƒƒãƒˆï¼ˆMCPç‰ˆï¼‰

on:
  workflow_call:
    inputs:
      text:
        description: 'éŸ³å£°åŒ–ã™ã‚‹ãƒ†ã‚­ã‚¹ãƒˆ'
        required: true
        type: string
      output_dir:
        description: 'å‡ºåŠ›ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªãƒ‘ã‚¹'
        required: true
        type: string
      voice:
        description: 'ãƒœã‚¤ã‚¹è¨­å®š'
        required: false
        type: string
        default: 'Professional Japanese female voice (Wise_Woman or similar)'
      language:
        description: 'è¨€èªžè¨­å®š'
        required: false
        type: string
        default: 'Japanese'
    outputs:
      audio_path:
        description: 'ç”Ÿæˆã•ã‚ŒãŸéŸ³å£°ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‘ã‚¹'
        value: ${{ jobs.generate.outputs.audio_path }}
      audio_url:
        description: 'éŸ³å£°URL'
        value: ${{ jobs.generate.outputs.audio_url }}
      duration:
        description: 'éŸ³å£°ã®é•·ã•ï¼ˆç§’ï¼‰'
        value: ${{ jobs.generate.outputs.duration }}
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN:
        description: 'Claude Code OAuth Token'
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      audio_path: ${{ steps.execute.outputs.audio_path }}
      audio_url: ${{ steps.execute.outputs.audio_url }}
      duration: ${{ steps.execute.outputs.duration }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: |
          npm init -y
          npm install @anthropic-ai/claude-code
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          
      - name: Generate Narration with MCP
        id: execute
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          CLAUDE_CODE_CI_MODE: true
          CLAUDE_CODE_AUTO_APPROVE_MCP: true
        run: |
          # ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªä½œæˆ
          mkdir -p "${{ inputs.output_dir }}"
          
          # Claude Codeãƒ—ãƒ­ãƒ³ãƒ—ãƒˆ
          CLAUDE_PROMPT="Generate narration audio using Text-to-Speech:

          **Text**: ${{ inputs.text }}
          **Voice**: ${{ inputs.voice }}
          **Language**: ${{ inputs.language }}

          Steps:
          1. Use mcp__t2s-kamui-minimax-speech-02-turbo__minimax_speech_02_turbo_submit to generate speech
          2. Monitor status with mcp__t2s-kamui-minimax-speech-02-turbo__minimax_speech_02_turbo_status
          3. Get result with mcp__t2s-kamui-minimax-speech-02-turbo__minimax_speech_02_turbo_result
          4. Save the audio URL to ${{ inputs.output_dir }}/narration-url.txt
          5. Download the audio to ${{ inputs.output_dir }}/narration.mp3 using curl
          6. Use ffprobe to get duration and save to ${{ inputs.output_dir }}/narration-duration.txt

          Make sure to wait for generation to complete before downloading."
          
          # Claude Codeå®Ÿè¡Œ
          npx @anthropic-ai/claude-code \
            -p "$CLAUDE_PROMPT" \
            --mcp-config ".claude/mcp-kamuicode.json" \
            --allowedTools "mcp__t2s-kamui-minimax-speech-02-turbo__minimax_speech_02_turbo_submit,mcp__t2s-kamui-minimax-speech-02-turbo__minimax_speech_02_turbo_status,mcp__t2s-kamui-minimax-speech-02-turbo__minimax_speech_02_turbo_result,Bash,Write" \
            --permission-mode "acceptEdits" || true
          
          # çµæžœç¢ºèªã¨ãƒ•ã‚©ãƒ¼ãƒ«ãƒãƒƒã‚¯
          if [ -f "${{ inputs.output_dir }}/narration.mp3" ]; then
            # ãƒ•ã‚¡ã‚¤ãƒ«ã‚µã‚¤ã‚ºã‚’ç¢ºèª
            FILE_SIZE=$(stat -c%s "${{ inputs.output_dir }}/narration.mp3" 2>/dev/null || echo "0")
            
            if [ "$FILE_SIZE" -gt 1000 ]; then
              # æœ‰åŠ¹ãªMP3ãƒ•ã‚¡ã‚¤ãƒ«ã®å ´åˆã®ã¿ffprobeã‚’å®Ÿè¡Œ
              DURATION=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${{ inputs.output_dir }}/narration.mp3" 2>/dev/null | cut -d. -f1)
              if [ -z "$DURATION" ]; then
                # ãƒ†ã‚­ã‚¹ãƒˆã®é•·ã•ã‹ã‚‰æŽ¨å®š
                TEXT_LENGTH=$(echo "${{ inputs.text }}" | wc -c)
                DURATION=$(echo "scale=1; $TEXT_LENGTH * 0.15" | bc -l)
              fi
            else
              # ãƒ—ãƒ¬ãƒ¼ã‚¹ãƒ›ãƒ«ãƒ€ãƒ¼ãƒ•ã‚¡ã‚¤ãƒ«ã®å ´åˆ
              TEXT_LENGTH=$(echo "${{ inputs.text }}" | wc -c)
              DURATION=$(echo "scale=1; $TEXT_LENGTH * 0.15" | bc -l)
            fi
            
            if [ -f "${{ inputs.output_dir }}/narration-url.txt" ]; then
              AUDIO_URL=$(cat "${{ inputs.output_dir }}/narration-url.txt" | head -1)
            else
              AUDIO_URL="local://narration.mp3"
            fi
          else
            echo "âš ï¸ Creating placeholder narration file..."
            # ãƒ—ãƒ¬ãƒ¼ã‚¹ãƒ›ãƒ«ãƒ€ãƒ¼ä½œæˆ
            mkdir -p "${{ inputs.output_dir }}"
            # æ–‡å­—æ•°ã‹ã‚‰é•·ã•ã‚’æŽ¨å®š
            TEXT_LENGTH=$(echo "${{ inputs.text }}" | wc -c)
            DURATION=$(echo "scale=1; $TEXT_LENGTH * 0.15" | bc -l)
            # ç„¡éŸ³ã®MP3ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ç”Ÿæˆ
            ffmpeg -f lavfi -i anullsrc=duration=$DURATION:sample_rate=44100 \
              -codec:a mp3 -b:a 128k \
              "${{ inputs.output_dir }}/narration.mp3" -y
            AUDIO_URL="placeholder"
          fi
          
          # ãƒ‡ãƒãƒƒã‚°æƒ…å ±ï¼ˆã‚¨ãƒ©ãƒ¼å›žé¿ã®ãŸã‚ç°¡æ½”ã«ï¼‰
          echo "ðŸ“Š Narration: path=${{ inputs.output_dir }}/narration.mp3, duration=$DURATION"
          
          # å‡ºåŠ›è¨­å®š
          echo "audio_path=${{ inputs.output_dir }}/narration.mp3" >> $GITHUB_OUTPUT
          echo "audio_url=$AUDIO_URL" >> $GITHUB_OUTPUT
          echo "duration=${DURATION:-30}" >> $GITHUB_OUTPUT