name: "Fallback Dynamic Workflow"
run-name: "🚀 Fallback Workflow | rossy8417"

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Execution mode'
        type: choice
        options: ['test', 'production']
        default: 'test'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Fallback Execution
        run: echo "Fallback workflow executed"
