name: ワークフロー生成リクエスト (Enhanced v3)
description: 複合テンプレート機能・段階的デプロイメント対応の新しいKamuicodeワークフロー生成リクエスト
title: "[Workflow Request] "
labels: ["workflow-generation", "automation", "v3-enhanced"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 Kamuicode Meta Workflow Generator v3
        **複合テンプレート機能・段階的デプロイメント・動的inputs対応**
        
        このフォームを使用して、AI生成サービス統合ワークフローを自動生成できます。
        複数のテンプレートを組み合わせた複合ワークフローの生成も可能です。
        
        ### ✨ **新機能**
        - 🔗 **複合テンプレート**: 複数のAI機能を自動組み合わせ（例：画像→動画→音楽）
        - 🎯 **動的inputs**: ユーザーフレンドリーな入力フォーム自動生成
        - 🛡️ **品質保証**: 段階的デプロイメント（Staging→Validation→Production）
        - 🤖 **MCP統合**: 最新AI生成サービス（T2I, I2V, T2M, V2A等）
        
  - type: dropdown
    id: workflow-category
    attributes:
      label: ワークフロー種別
      description: 生成したいワークフローの種別を選択してください
      options:
        - "単一機能ワークフロー（従来型）"
        - "複合統合ワークフロー（複数AI機能組み合わせ）" 
        - "カスタム・実験的ワークフロー"
    validations:
      required: true

  - type: dropdown
    id: primary-workflow-type
    attributes:
      label: 主要ワークフロータイプ
      description: メインとなるワークフローのタイプを選択
      options:
        - "画像生成（image-generation）- T2I"
        - "動画生成（video-generation）- T2V/I2V"
        - "音声・音楽生成（audio-generation）- T2M/V2A"
        - "3Dモデル生成（3d-model）- I2I3D"
        - "プレゼンテーション作成（presentation）"
        - "データ分析・可視化（data-analysis）"
        - "ニュース記事生成（news-article）"
        - "ブログ記事作成（blog-article）"
        - "マルチメディア広告（multimedia-ad）"
        - "カスタム（custom）"
    validations:
      required: true

  - type: checkboxes
    id: composite-features
    attributes:
      label: 複合機能（複数選択で自動組み合わせ）
      description: 組み合わせたいAI機能を選択（複数選択で複合ワークフロー生成）
      options:
        - label: "🎨 T2I - テキストから画像生成（Imagen4, Google Imagen3）"
        - label: "🎬 T2V - テキストから動画生成（Veo3 Fast）"
        - label: "🖼️ I2V - 画像から動画生成（Hailuo-02 Pro）"
        - label: "🎵 T2M - テキストから音楽生成（Google Lyria）"
        - label: "🔊 V2A - 動画から音声生成（ThinkSound）"
        - label: "📐 I2I3D - 画像から3Dモデル生成（Hunyuan3D）"
        - label: "🎞️ V2V - 動画変換・修正（Luma Ray-2）"
        - label: "🎪 R2V - 参照画像から動画生成（Vidu Q1）"

  - type: textarea
    id: detailed-description
    attributes:
      label: 詳細な説明・ストーリー
      description: |
        生成したいワークフローの詳細を記述してください。
        複合ワークフローの場合は、各機能間の連携方法も記載してください。
      placeholder: |
        【単一機能の例】
        - 毎日午前9時にその日の天気に合わせたイラストを自動生成したい
        - プロダクト画像から3Dモデルを生成してARアプリで使用したい
        
        【複合機能の例】
        - ストーリーテキストから画像生成→動画化→BGM追加→完成動画出力
        - ニュース記事から要約画像生成→プレゼンスライド作成→ナレーション音声追加
        - 商品説明から画像生成→3Dモデル化→プロモーション動画作成
      value: |
        ## ワークフローの目的・背景
        
        
        ## 期待する処理フロー
        1. 
        2. 
        3. 
        
        ## 最終成果物
        
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: 技術的要件・制約
      description: MCP設定、出力形式、品質設定などの技術仕様
      placeholder: |
        【出力仕様】
        - 画像：1920x1080、16:9、PNG/JPEG
        - 動画：MP4、H.264、30fps、4-8秒
        - 音楽：MP3、44.1kHz、ステレオ、30-60秒
        
        【品質設定】
        - 画像品質：Ultra（最高品質）/ Balanced（バランス）/ Fast（高速）
        - 処理優先度：品質重視 / 速度重視 / バランス
        
        【MCP設定】
        - 使用優先サービス：imagen4-ultra, veo3-fast, google-lyria など
        
        【実行制約】
        - 最大実行時間：○○分
        - 並列処理数：○○個
        - リトライ回数：○○回
      value: |
        ## 出力形式・品質
        
        
        ## MCP設定・AI生成サービス
        
        
        ## 実行・パフォーマンス制約
        
        
    validations:
      required: false

  - type: checkboxes
    id: advanced-features
    attributes:
      label: 高度な機能・最適化
      description: ワークフローに含めたい高度な機能を選択
      options:
        - label: "🎯 動的inputs - ユーザーフレンドリーな入力フォーム生成"
        - label: "🔄 段階的デプロイメント - Staging→Validation→Production"
        - label: "⚡ 並列処理 - 複数タスクの同時実行"
        - label: "🛡️ 品質検証 - 自動品質チェック・向上処理"
        - label: "🔧 自動修復 - エラー検出時の自動修正"
        - label: "📊 進捗監視 - リアルタイム実行状況監視"
        - label: "💾 中間ファイル保存 - 各段階の結果ファイル保存"
        - label: "🔀 フォールバック - 代替サービス・手法による継続実行"
        - label: "⏰ 定期実行 - スケジュール実行機能"
        - label: "🔔 通知機能 - 完了・エラー通知"

  - type: dropdown
    id: deployment-mode
    attributes:
      label: デプロイメントモード
      description: ワークフローの配置・実行方式を選択
      options:
        - "本番直接配置（通常モード）"
        - "段階的デプロイメント（推奨：Staging→Validation→Production）"
        - "テスト専用配置（実験・検証用）"
      default: 1
    validations:
      required: true

  - type: dropdown
    id: urgency-level
    attributes:
      label: 緊急度・優先度
      description: 生成リクエストの優先度を選択
      options:
        - "低（通常処理）"
        - "中（優先処理）"
        - "高（緊急処理）"
      default: 0
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: 成功判定条件・期待結果
      description: |
        ワークフローが正常に動作したと判定する条件を記載
        生成されるファイルや実行結果の期待値を具体的に記述
      placeholder: |
        【成功条件の例】
        ✅ 指定した品質基準（75点以上）を満たす画像が生成される
        ✅ 動画とBGMが正しく合成された最終ファイルが出力される  
        ✅ 全処理が10分以内に完了する
        ✅ エラー発生時に適切なフォールバック処理が動作する
        
        【期待結果】
        - 最終成果物：○○形式のファイル
        - 中間成果物：各段階での○○ファイル
        - ログ・レポート：実行結果詳細レポート
      value: |
        ## 成功判定条件
        ✅ 
        ✅ 
        ✅ 
        
        ## 期待される最終成果物
        
        
        ## 期待される中間成果物
        
        
    validations:
      required: false

  - type: textarea
    id: stepback-questions-static
    attributes:
      label: 📋 詳細確認質問（ワークフロー最適化のため）
      description: |
        **より正確で最適化されたワークフローを生成するため、以下の質問にお答えください。**
        
        質問に回答後、Issue作成時に下記の「ワークフロー実行指示」セクションに
        「**start**」とコメントすることで、GitHub Actionが開始されます。
        
        **📝 回答方法:**
        1. 以下の質問に回答を記入
        2. Issue作成
        3. 「ワークフロー実行指示」セクションに「**start**」をコメント
      value: |
        ## 📋 ワークフロー詳細化のための質問
        
        より正確で最適化されたワークフローを生成するために、以下の質問にお答えください：
        
        **Q1: 出力品質・形式について**
        生成する画像/動画/音声の品質設定や形式について教えてください。
        - 画像解像度：1920x1080 / 1280x720 / その他（　　　）
        - 動画品質：高品質（時間重視せず） / バランス / 高速（品質妥協）
        - 音声品質：高品質（320kbps） / 標準（128kbps） / 圧縮優先
        - ファイル形式：標準（PNG/MP4/MP3） / 特定形式希望（　　　）
        
        **回答：**（ここに詳細をお書きください）
        
        
        **Q2: 処理フロー・順序について**
        複数のメディアファイルを生成する場合の処理方法について教えてください。
        - 処理順序：特定の順序が必要 / 並列処理可能 / お任せ
        - 依存関係：前段階の出力を次で使用 / 独立して生成
        - 処理優先度：品質重視（時間不問） / 速度重視 / バランス型
        
        **回答：**（ここに詳細をお書きください）
        
        
        **Q3: 技術仕様・制約について**
        技術的な要件や制約について教えてください。
        - 実行時間：品質重視（時間不問） / 60分以内 / 30分以内
        - MCPサービス：特定サービス希望 / 推奨設定でOK / 高速サービス優先
        - エラー処理：厳密（エラー時停止） / 寛容（継続実行） / 自動リトライ
        
        **回答：**（ここに詳細をお書きください）
        
        
        **Q4: コンテンツ仕様について**
        生成するコンテンツの詳細仕様について教えてください。
        - 画像スタイル：リアル系 / アニメ系 / 抽象系 / お任せ
        - 動画の長さ：短編（3-5秒） / 標準（8-10秒） / 長編（15秒以上）
        - 音楽ジャンル：指定あり（　　　） / ムード重視 / お任せ
        
        **回答：**（ここに詳細をお書きください）
        
        
        **Q5: 統合・連携について**
        各段階の出力を次段階でどう活用するかについて教えてください。
        - 画像→動画連携：画像をベースに動画生成 / 独立して動画作成
        - 音楽との同期：動画と音楽の同期希望 / 独立ファイルでOK
        - 最終統合：すべて統合した1つのファイル / 個別ファイルで提供
        
        **回答：**（ここに詳細をお書きください）
        
        ---
        
        ### 📝 回答完了後の手順
        1. 上記の質問に回答を記入してIssue作成
        2. 下記「ワークフロー実行指示」に「**start**」をコメント
        3. 自動的にワークフロー生成・実行が開始されます
    validations:
      required: true

  - type: textarea
    id: workflow-execution-command
    attributes:
      label: 🚀 ワークフロー実行指示
      description: |
        **上記の質問に回答完了後、以下に「実行開始」と記入してIssue作成してください。**
        
        Issue作成後、ここに「**start**」とコメントすることで、
        あなたの回答を解析してカスタムワークフローを生成・実行します。
        
        **⚠️ 重要**: この部分は空欄のままでIssue作成し、
        その後にコメントで「**start**」と投稿してください。
      placeholder: |
        （ここは空欄のままでIssue作成してください）
        
        📝 Issue作成後の手順：
        1. このIssueにコメントを投稿
        2. コメント内容に「start」と記入
        3. 自動的にワークフロー生成が開始されます
        
        例：
        start
        
        または：
        start workflow generation
      value: |
        **📝 Issue作成後の実行指示方法**
        
        1. Issue作成後、このIssueにコメントを投稿
        2. コメント内容に「**start**」と記入
        3. 自動的にワークフロー生成が開始されます
        
        **実行開始コマンド例:**
        ```
        start
        ```
        
        または
        
        ```
        start workflow generation
        ```
        
        ---
        
        **🔄 処理状況の確認方法:**
        - Issue作成後にコメント投稿でワークフロー開始
        - 実行状況はGitHub Actionsタブで確認可能
        - 完了後にこのIssueに結果が通知されます
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 🔄 ステップバック質問システム v5（改良版）
        
        ### 📋 実行プロセス
        
        1. **📝 質問回答**: 上記の詳細確認質問に回答
        2. **📮 Issue作成**: 回答内容とともにIssue作成
        3. **🚀 実行指示**: コメントで「実行開始」を投稿
        4. **🤖 AI解析**: あなたの回答を分析してワークフロー要求を詳細化
        5. **🛠️ ワークフロー生成**: 最適化されたカスタムワークフロー作成
        6. **🚀 段階的配置**: Staging→Validation→Production デプロイメント
        7. **📊 結果通知**: 生成完了・実行可能ワークフロー提供
        
        ### 🎯 v5 新機能
        - **事前質問システム**: Issue Template内に質問を組み込み済み
        - **コメント実行トリガー**: 確実なワークフロー開始制御
        - **回答解析システム**: ユーザー回答に基づく高精度ワークフロー生成
        - **シンプル操作**: 複雑な動的生成を廃し、確実な静的質問システム
        
        **Generated by Kamuicode Meta Workflow Generator v5** 🚀✨