name: ワークフロー生成リクエスト (Enhanced v3)
description: 複合テンプレート機能・段階的デプロイメント対応の新しいKamuicodeワークフロー生成リクエスト
title: "[Workflow Request] "
labels: ["workflow-generation", "automation", "v3-enhanced"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 Kamuicode Meta Workflow Generator v3
        **複合テンプレート機能・段階的デプロイメント・動的inputs対応**
        
        このフォームを使用して、AI生成サービス統合ワークフローを自動生成できます。
        複数のテンプレートを組み合わせた複合ワークフローの生成も可能です。
        
        ### ✨ **新機能**
        - 🔗 **複合テンプレート**: 複数のAI機能を自動組み合わせ（例：画像→動画→音楽）
        - 🎯 **動的inputs**: ユーザーフレンドリーな入力フォーム自動生成
        - 🛡️ **品質保証**: 段階的デプロイメント（Staging→Validation→Production）
        - 🤖 **MCP統合**: 最新AI生成サービス（T2I, I2V, T2M, V2A等）
        
  - type: dropdown
    id: workflow-category
    attributes:
      label: ワークフロー種別
      description: 生成したいワークフローの種別を選択してください
      options:
        - "単一機能ワークフロー（従来型）"
        - "複合統合ワークフロー（複数AI機能組み合わせ）" 
        - "カスタム・実験的ワークフロー"
    validations:
      required: true

  - type: dropdown
    id: primary-workflow-type
    attributes:
      label: 主要ワークフロータイプ
      description: メインとなるワークフローのタイプを選択
      options:
        - "画像生成（image-generation）- T2I"
        - "動画生成（video-generation）- T2V/I2V"
        - "音声・音楽生成（audio-generation）- T2M/V2A"
        - "3Dモデル生成（3d-model）- I2I3D"
        - "プレゼンテーション作成（presentation）"
        - "データ分析・可視化（data-analysis）"
        - "ニュース記事生成（news-article）"
        - "ブログ記事作成（blog-article）"
        - "マルチメディア広告（multimedia-ad）"
        - "カスタム（custom）"
    validations:
      required: true

  - type: checkboxes
    id: composite-features
    attributes:
      label: 複合機能（複数選択で自動組み合わせ）
      description: 組み合わせたいAI機能を選択（複数選択で複合ワークフロー生成）
      options:
        - label: "🎨 T2I - テキストから画像生成（Imagen4, Google Imagen3）"
        - label: "🎬 T2V - テキストから動画生成（Veo3 Fast）"
        - label: "🖼️ I2V - 画像から動画生成（Hailuo-02 Pro）"
        - label: "🎵 T2M - テキストから音楽生成（Google Lyria）"
        - label: "🔊 V2A - 動画から音声生成（ThinkSound）"
        - label: "📐 I2I3D - 画像から3Dモデル生成（Hunyuan3D）"
        - label: "🎞️ V2V - 動画変換・修正（Luma Ray-2）"
        - label: "🎪 R2V - 参照画像から動画生成（Vidu Q1）"

  - type: textarea
    id: detailed-description
    attributes:
      label: 詳細な説明・ストーリー
      description: |
        生成したいワークフローの詳細を記述してください。
        複合ワークフローの場合は、各機能間の連携方法も記載してください。
      placeholder: |
        【単一機能の例】
        - 毎日午前9時にその日の天気に合わせたイラストを自動生成したい
        - プロダクト画像から3Dモデルを生成してARアプリで使用したい
        
        【複合機能の例】
        - ストーリーテキストから画像生成→動画化→BGM追加→完成動画出力
        - ニュース記事から要約画像生成→プレゼンスライド作成→ナレーション音声追加
        - 商品説明から画像生成→3Dモデル化→プロモーション動画作成
      value: |
        ## ワークフローの目的・背景
        
        
        ## 期待する処理フロー
        1. 
        2. 
        3. 
        
        ## 最終成果物
        
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: 技術的要件・制約
      description: MCP設定、出力形式、品質設定などの技術仕様
      placeholder: |
        【出力仕様】
        - 画像：1920x1080、16:9、PNG/JPEG
        - 動画：MP4、H.264、30fps、4-8秒
        - 音楽：MP3、44.1kHz、ステレオ、30-60秒
        
        【品質設定】
        - 画像品質：Ultra（最高品質）/ Balanced（バランス）/ Fast（高速）
        - 処理優先度：品質重視 / 速度重視 / バランス
        
        【MCP設定】
        - 使用優先サービス：imagen4-ultra, veo3-fast, google-lyria など
        
        【実行制約】
        - 最大実行時間：○○分
        - 並列処理数：○○個
        - リトライ回数：○○回
      value: |
        ## 出力形式・品質
        
        
        ## MCP設定・AI生成サービス
        
        
        ## 実行・パフォーマンス制約
        
        
    validations:
      required: false

  - type: checkboxes
    id: advanced-features
    attributes:
      label: 高度な機能・最適化
      description: ワークフローに含めたい高度な機能を選択
      options:
        - label: "🎯 動的inputs - ユーザーフレンドリーな入力フォーム生成"
        - label: "🔄 段階的デプロイメント - Staging→Validation→Production"
        - label: "⚡ 並列処理 - 複数タスクの同時実行"
        - label: "🛡️ 品質検証 - 自動品質チェック・向上処理"
        - label: "🔧 自動修復 - エラー検出時の自動修正"
        - label: "📊 進捗監視 - リアルタイム実行状況監視"
        - label: "💾 中間ファイル保存 - 各段階の結果ファイル保存"
        - label: "🔀 フォールバック - 代替サービス・手法による継続実行"
        - label: "⏰ 定期実行 - スケジュール実行機能"
        - label: "🔔 通知機能 - 完了・エラー通知"

  - type: dropdown
    id: deployment-mode
    attributes:
      label: デプロイメントモード
      description: ワークフローの配置・実行方式を選択
      options:
        - "本番直接配置（通常モード）"
        - "段階的デプロイメント（推奨：Staging→Validation→Production）"
        - "テスト専用配置（実験・検証用）"
      default: 1
    validations:
      required: true

  - type: dropdown
    id: urgency-level
    attributes:
      label: 緊急度・優先度
      description: 生成リクエストの優先度を選択
      options:
        - "低（通常処理）"
        - "中（優先処理）"
        - "高（緊急処理）"
      default: 0
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: 成功判定条件・期待結果
      description: |
        ワークフローが正常に動作したと判定する条件を記載
        生成されるファイルや実行結果の期待値を具体的に記述
      placeholder: |
        【成功条件の例】
        ✅ 指定した品質基準（75点以上）を満たす画像が生成される
        ✅ 動画とBGMが正しく合成された最終ファイルが出力される  
        ✅ 全処理が10分以内に完了する
        ✅ エラー発生時に適切なフォールバック処理が動作する
        
        【期待結果】
        - 最終成果物：○○形式のファイル
        - 中間成果物：各段階での○○ファイル
        - ログ・レポート：実行結果詳細レポート
      value: |
        ## 成功判定条件
        ✅ 
        ✅ 
        ✅ 
        
        ## 期待される最終成果物
        
        
        ## 期待される中間成果物
        
        
    validations:
      required: false

  - type: textarea
    id: dynamic-stepback-placeholder
    attributes:
      label: 📋 詳細確認質問（自動生成予定）
      description: |
        **このセクションは自動更新されます**
        
        Issue作成後、AIがあなたの要求を分析し、より正確なワークフロー生成のために
        必要な詳細確認質問を自動的にここに追加します。
        
        **処理フロー:**
        1. Issue作成 → AI分析実行
        2. カスタム質問生成 → この部分に自動挿入
        3. 質問への回答 → Issue編集で回答追加
        4. ワークフロー生成開始 → 最適化されたワークフロー作成
      placeholder: |
        【自動生成される質問の例】
        
        **Q1: 出力品質・形式について**
        画像/動画の解像度、品質設定、ファイル形式について具体的な要求はありますか？
        回答：（Issue作成後、ここに実際の質問が表示されます）
        
        **Q2: 処理フロー・順序について**
        複数のメディアファイルを生成する場合、処理の順序や並列実行の希望はありますか？
        回答：（AI分析後、カスタマイズされた質問が生成されます）
        
        **Q3: 技術仕様・制約について**
        特定のMCPサービスや実行時間制限などの技術的要件はありますか？
        回答：（あなたの要求に応じた具体的質問が生成されます）
        
        ---
        
        ⚠️ **注意**: この部分は Issue作成後に自動更新されます。
        手動で編集する必要はありません。
      value: |
        ## 📋 詳細確認質問（自動生成待ち）
        
        **🤖 AI分析中...**
        
        Issue作成後、あなたの要求内容を分析し、最適化されたワークフロー生成のために
        必要な具体的質問をここに自動生成します。
        
        **生成される質問の種類:**
        - 出力品質・形式の詳細
        - 処理フロー・順序の希望
        - 技術仕様・制約の確認
        - コンテンツ仕様の明確化
        - 統合・連携の方針
        
        **📝 回答方法:**
        1. AI質問生成完了の通知を待つ
        2. このIssueを編集して質問に回答
        3. Issue保存で自動的にワークフロー生成開始
        
        ---
        
        🔄 **処理状況:** 初期要求受付完了 → AI分析開始予定
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 🔄 動的ステップバック質問システム v4
        
        ### 📋 生成プロセス
        
        1. **🔍 初期分析**: ユーザー要求の分析（`meta/prompts/stepback-question-generator.md`）
        2. **❓ 質問生成**: Claude Code による動的質問生成・Issue自動更新
        3. **✅ 回答待ち**: ユーザーによる詳細回答（Issue編集）
        4. **🛠️ ワークフロー生成**: 詳細化された要求によるカスタムワークフロー作成
        5. **🚀 段階的配置**: Staging→Validation→Production デプロイメント
        6. **📊 結果通知**: 生成完了・実行可能ワークフロー提供
        
        ### 🎯 新機能
        - **動的質問生成**: ユーザー要求に応じたカスタム質問
        - **Issue内完結**: 1つのIssue内で質問→回答→生成の完全な流れ
        - **AI分析強化**: プロンプトファイル活用による高精度分析
        - **依存関係管理**: ファイルパス統合による一貫性保証
        
        **Generated by Kamuicode Meta Workflow Generator v4** 🤖✨