name: ワークフロー生成リクエスト
description: 新しいKamuicodeワークフローの生成をリクエスト
title: "[Workflow Request] "
labels: ["workflow-generation", "automation"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 ワークフロー生成リクエスト
        このフォームを使用して、新しいKamuicodeワークフローの自動生成をリクエストできます。
        
  - type: dropdown
    id: workflow-type
    attributes:
      label: ワークフローのタイプ
      description: 生成したいワークフローのタイプを選択してください
      options:
        - 画像生成（image-generation）
        - 動画生成（video-generation）
        - 音声生成（audio-generation）
        - ニュース記事生成（news-article）
        - ニュース動画生成（news-video）
        - ソーシャル連携（social-integration）
        - カスタム（custom）
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: 詳細な説明
      description: 生成したいワークフローの詳細を記述してください
      placeholder: |
        例：
        - 毎日午前9時に今日の天気に合わせたイラストを生成したい
        - 新しいイシューが作成されたら自動でサムネイルを生成したい
        - 最新のAIニュースを収集して動画化したい
    validations:
      required: true
      
  - type: textarea
    id: requirements
    attributes:
      label: 具体的な要件
      description: 必要な機能や制約を記載してください
      placeholder: |
        - 出力形式: 1920x1080のPNG画像
        - 実行頻度: 毎日午前9時
        - 使用モデル: DALL-E 3
        - エラー時の通知: Slack
        
  - type: checkboxes
    id: features
    attributes:
      label: 必要な機能
      description: ワークフローに含めたい機能を選択してください
      options:
        - label: 定期実行（スケジュール）
        - label: エラー通知
        - label: 複数ファイル出力
        - label: 並列処理
        - label: キャッシュ機能
        - label: Web検索機能
        - label: 外部API連携
        - label: 品質検証