name: data-analysis
description: データ分析の最小単位ユニット

on:
  workflow_call:
    inputs:
      data_path:
        description: '分析するデータファイルパス'
        required: true
        type: string
      output_dir:
        description: '出力ディレクトリパス'
        required: true
        type: string
      analysis_type:
        description: '分析タイプ（statistical/trend/correlation/summary）'
        required: false
        type: string
        default: 'summary'
      generate_visualizations:
        description: 'グラフを生成するか'
        required: false
        type: boolean
        default: true
    outputs:
      analysis_path:
        description: '分析結果ファイルパス'
        value: ${{ jobs.analyze.outputs.analysis_path }}
      summary:
        description: '分析サマリー'
        value: ${{ jobs.analyze.outputs.summary }}
      visualization_count:
        description: '生成されたグラフ数'
        value: ${{ jobs.analyze.outputs.visualization_count }}
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN:
        description: 'Anthropic API Key'
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    outputs:
      analysis_path: ${{ steps.execute.outputs.analysis_path }}
      summary: ${{ steps.execute.outputs.summary }}
      visualization_count: ${{ steps.execute.outputs.visualization_count }}
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install pandas matplotlib seaborn numpy
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Claude Code SDK
        run: npm install @anthropic-ai/claude-code
      
      - name: Analyze Data
        id: execute
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          # ディレクトリ作成
          mkdir -p "${{ inputs.output_dir }}"
          
          # 分析プロンプトの構築
          ANALYSIS_PROMPT="Analyze the data file at '${{ inputs.data_path }}' with the following requirements:

          Analysis Type: ${{ inputs.analysis_type }}
          
          Tasks:
          1. Load and examine the data structure
          2. Perform ${{ inputs.analysis_type }} analysis
          3. Generate insights and findings
          4. Create a detailed analysis report
          5. Save results to '${{ inputs.output_dir }}/analysis_report.json'
          
          For ${{ inputs.analysis_type }} analysis, include:
          - Statistical: mean, median, std dev, quartiles, outliers
          - Trend: time series patterns, growth rates, seasonality
          - Correlation: variable relationships, correlation matrix
          - Summary: key metrics, data quality, main findings
          
          Generate visualizations: ${{ inputs.generate_visualizations }}
          If true, create appropriate charts and save as PNG files.
          
          Report format:
          {
            \"summary\": \"Brief overview\",
            \"key_findings\": [],
            \"statistics\": {},
            \"recommendations\": [],
            \"visualizations\": []
          }"
          
          # Claude Code実行
          npx @anthropic-ai/claude-code \
            --allowedTools "Read,Write,Bash" \
            --max-turns 20 \
            --permission-mode "acceptEdits" \
            -p "$ANALYSIS_PROMPT"
          
          # 結果確認
          if [ -f "${{ inputs.output_dir }}/analysis_report.json" ]; then
            SUMMARY=$(cat "${{ inputs.output_dir }}/analysis_report.json" | jq -r '.summary // "Analysis completed"')
            VIZ_COUNT=$(find "${{ inputs.output_dir }}" -name "*.png" | wc -l)
            
            echo "analysis_path=${{ inputs.output_dir }}/analysis_report.json" >> $GITHUB_OUTPUT
            echo "summary=$SUMMARY" >> $GITHUB_OUTPUT
            echo "visualization_count=$VIZ_COUNT" >> $GITHUB_OUTPUT
          else
            # フォールバック
            echo "{\"error\": \"Analysis failed\"}" > "${{ inputs.output_dir }}/analysis_report.json"
            echo "analysis_path=${{ inputs.output_dir }}/analysis_report.json" >> $GITHUB_OUTPUT
            echo "summary=Analysis failed" >> $GITHUB_OUTPUT
            echo "visualization_count=0" >> $GITHUB_OUTPUT
          fi