name: git-pr-create
description: GitHubãƒ—ãƒ«ãƒªã‚¯ã‚¨ã‚¹ãƒˆä½œæˆã®æœ€å°å˜ä½ãƒ¦ãƒ‹ãƒƒãƒˆ

on:
  workflow_call:
    inputs:
      branch_name:
        description: 'PRã‚’ä½œæˆã™ã‚‹ãƒ–ãƒ©ãƒ³ãƒå'
        required: true
        type: string
      base_branch:
        description: 'ãƒžãƒ¼ã‚¸å…ˆã®ãƒ™ãƒ¼ã‚¹ãƒ–ãƒ©ãƒ³ãƒ'
        required: false
        type: string
        default: 'main'
      title:
        description: 'PRã®ã‚¿ã‚¤ãƒˆãƒ«'
        required: true
        type: string
      body_file:
        description: 'PRæœ¬æ–‡ã®ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‘ã‚¹'
        required: false
        type: string
      labels:
        description: 'PRã«ä»˜ã‘ã‚‹ãƒ©ãƒ™ãƒ«ï¼ˆã‚«ãƒ³ãƒžåŒºåˆ‡ã‚Šï¼‰'
        required: false
        type: string
        default: 'automated'
    outputs:
      pr_url:
        description: 'ä½œæˆã•ã‚ŒãŸPRã®URL'
        value: ${{ jobs.create-pr.outputs.pr_url }}
      pr_number:
        description: 'PRç•ªå·'
        value: ${{ jobs.create-pr.outputs.pr_number }}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    outputs:
      pr_url: ${{ steps.create.outputs.pr_url }}
      pr_number: ${{ steps.create.outputs.pr_number }}
    
    steps:
      - name: Create Pull Request
        id: create
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # PRæœ¬æ–‡ã®æº–å‚™
          if [ -n "${{ inputs.body_file }}" ] && [ -f "${{ inputs.body_file }}" ]; then
            PR_BODY=$(cat "${{ inputs.body_file }}")
          else
            PR_BODY="Automated pull request from workflow

            Branch: ${{ inputs.branch_name }}
            
            ðŸ¤– Generated with Claude Code"
          fi
          
          # PRã®ä½œæˆ
          PR_OUTPUT=$(gh pr create \
            --title "${{ inputs.title }}" \
            --body "$PR_BODY" \
            --base "${{ inputs.base_branch }}" \
            --head "${{ inputs.branch_name }}" \
            --label "${{ inputs.labels }}" \
            2>&1) || {
            echo "PR creation failed. Output: $PR_OUTPUT"
            
            # PRãŒæ—¢ã«å­˜åœ¨ã™ã‚‹å ´åˆã®å‡¦ç†
            if echo "$PR_OUTPUT" | grep -q "already exists"; then
              echo "PR already exists for this branch"
              # æ—¢å­˜ã®PRæƒ…å ±ã‚’å–å¾—
              PR_INFO=$(gh pr list --head "${{ inputs.branch_name }}" --json url,number --jq '.[0]')
              PR_URL=$(echo "$PR_INFO" | jq -r '.url')
              PR_NUMBER=$(echo "$PR_INFO" | jq -r '.number')
              echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
              echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
              exit 0
            else
              exit 1
            fi
          }
          
          # PR URLã¨NumberæŠ½å‡º
          PR_URL=$(echo "$PR_OUTPUT" | grep -oE 'https://github.com/[^/]+/[^/]+/pull/[0-9]+' | head -1)
          PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
          
          echo "âœ… PR created: $PR_URL"
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT