name: article-generation
description: 記事生成の最小単位ユニット

on:
  workflow_call:
    inputs:
      content_type:
        description: 'コンテンツタイプ（article, report, guide, etc.）'
        required: false
        type: string
        default: 'article'
      verified_script:
        description: '検証済みスクリプト/コンテンツ'
        required: true
        type: string
      output_dir:
        description: '出力ディレクトリパス'
        required: true
        type: string
      style:
        description: '記事スタイル'
        required: false
        type: string
        default: 'informative'
      target_length:
        description: '目標文字数'
        required: false
        type: string
        default: '1000'
    outputs:
      article_path:
        description: '生成された記事のパス'
        value: ${{ jobs.generate.outputs.article_path }}
      word_count:
        description: '記事の単語数'
        value: ${{ jobs.generate.outputs.word_count }}
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN:
        description: 'Anthropic API Key'
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      article_path: ${{ steps.execute.outputs.article_path }}
      word_count: ${{ steps.execute.outputs.word_count }}
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Claude Code SDK
        run: npm install @anthropic-ai/claude-code
      
      - name: Generate Article
        id: execute
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          # ディレクトリ作成
          mkdir -p "${{ inputs.output_dir }}"
          
          # プロンプト構築
          CONTENT_TYPE="${{ inputs.content_type }}"
          OUTPUT_FILE="${{ inputs.output_dir }}/${CONTENT_TYPE}.md"
          
          PROMPT="Generate a well-structured ${CONTENT_TYPE} based on the following content:

          **Verified Content**: ${{ inputs.verified_script }}
          **Style**: ${{ inputs.style }}
          **Target Length**: ${{ inputs.target_length }} words
          
          Requirements:
          1. Create an engaging title for the ${CONTENT_TYPE}
          2. Write a compelling introduction
          3. Structure the content with clear sections
          4. Include relevant examples and explanations
          5. Add a conclusion
          6. Save as Markdown to ${OUTPUT_FILE}
          
          The ${CONTENT_TYPE} should be:
          - Well-researched and factual
          - Easy to read and understand
          - Properly formatted with headers
          - Include relevant keywords naturally"
          
          # Claude Code実行
          npx @anthropic-ai/claude-code \
            --allowedTools "Write" \
            --max-turns 10 \
            --permission-mode "acceptEdits" \
            -p "$PROMPT"
          
          # 結果確認と単語数カウント
          if [ -f "${OUTPUT_FILE}" ]; then
            WORD_COUNT=$(wc -w < "${OUTPUT_FILE}")
            echo "article_path=${OUTPUT_FILE}" >> $GITHUB_OUTPUT
            echo "word_count=$WORD_COUNT" >> $GITHUB_OUTPUT
          else
            echo "❌ ${CONTENT_TYPE} generation failed"
            exit 1
          fi