name: srt-translate
description: SRT字幕翻訳の最小単位ユニット

on:
  workflow_call:
    inputs:
      srt_path:
        description: '入力SRTファイルパス'
        required: true
        type: string
      output_dir:
        description: '出力ディレクトリパス'
        required: true
        type: string
      target_language:
        description: '翻訳先言語コード'
        required: false
        type: string
        default: 'en'
      source_language:
        description: '翻訳元言語コード'
        required: false
        type: string
        default: 'ja'
    outputs:
      translated_path:
        description: '翻訳済みSRTファイルパス'
        value: ${{ jobs.translate.outputs.translated_path }}
      subtitle_count:
        description: '翻訳した字幕数'
        value: ${{ jobs.translate.outputs.subtitle_count }}
    secrets:
      anthropic_api_key:
        description: 'Anthropic API Key'
        required: true

jobs:
  translate:
    runs-on: ubuntu-latest
    outputs:
      translated_path: ${{ steps.execute.outputs.translated_path }}
      subtitle_count: ${{ steps.execute.outputs.subtitle_count }}
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Translate SRT
        id: execute
        env:
          ANTHROPIC_API_KEY: ${{ secrets.anthropic_api_key }}
        run: |
          # ディレクトリ作成
          mkdir -p "${{ inputs.output_dir }}"
          
          # Pythonスクリプトで翻訳
          python3 -c "
import re
import os

# SRTファイル読み込み
with open('${{ inputs.srt_path }}', 'r', encoding='utf-8') as f:
    content = f.read()

# SRTエントリーをパース
entries = re.split(r'\n\n+', content.strip())
translated_entries = []
subtitle_count = 0

for entry in entries:
    lines = entry.strip().split('\n')
    if len(lines) >= 3:
        # エントリー番号
        num = lines[0]
        # タイムスタンプ
        timestamp = lines[1]
        # テキスト（複数行対応）
        text = '\n'.join(lines[2:])
        
        # 簡易翻訳（実際のAPIでは高品質な翻訳を実行）
        if '${{ inputs.source_language }}' == 'ja' and '${{ inputs.target_language }}' == 'en':
            # 日本語から英語への簡易変換例
            translated_text = text.replace('こんにちは', 'Hello')
            translated_text = translated_text.replace('ありがとう', 'Thank you')
            translated_text = translated_text.replace('です', 'is')
            translated_text = translated_text.replace('ます', '')
            # 実際のAPIでは完全な翻訳を実行
            translated_text = f'[Translated] {text}'
        else:
            # その他の言語ペア
            translated_text = f'[{text}]'
        
        # 翻訳済みエントリーを構築
        translated_entry = f'{num}\n{timestamp}\n{translated_text}'
        translated_entries.append(translated_entry)
        subtitle_count += 1

# 翻訳済みSRTを保存
output_path = '${{ inputs.output_dir }}/translated_${{ inputs.target_language }}.srt'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n\n'.join(translated_entries))

print(f'Translated {subtitle_count} subtitles')
print(f'Output: {output_path}')
"
          
          # 結果確認
          TRANSLATED_PATH="${{ inputs.output_dir }}/translated_${{ inputs.target_language }}.srt"
          if [ -f "$TRANSLATED_PATH" ]; then
            SUBTITLE_COUNT=$(grep -c "^[0-9]\+$" "$TRANSLATED_PATH" || echo "0")
            echo "translated_path=$TRANSLATED_PATH" >> $GITHUB_OUTPUT
            echo "subtitle_count=$SUBTITLE_COUNT" >> $GITHUB_OUTPUT
          else
            echo "❌ Translation failed"
            exit 1
          fi