name: "Earthquake News Video Generation - Fallback"
run-name: "🚀 地震ニュース動画生成 (フォールバック版) | ${{ github.actor }} | Run #${{ github.run_number }}"

on:
  workflow_dispatch:
    inputs:
      concept:
        description: '地震ニュース動画のコンセプト'
        type: string
        default: '最新地震情報の日本語ニュース動画（1分、字幕付き）'
      earthquake_region:
        description: '地震発生地域（検索対象地域）'
        type: string
        default: '日本全国'

env:
  CLAUDE_CODE_CI_MODE: true
  CLAUDE_CODE_AUTO_APPROVE_MCP: true

jobs:
  fallback-workflow:
    runs-on: ubuntu-latest
    outputs:
      workflow_status: ${{ steps.execute.outputs.status }}
      
    steps:
      - name: Execute Fallback Workflow
        id: execute
        run: |
          echo "🚀 地震ニュース動画生成フォールバック版を実行中..."
          echo "💡 コンセプト: ${{ inputs.concept }}"
          echo "📍 対象地域: ${{ inputs.earthquake_region }}"
          
          # Create project directories
          mkdir -p projects/earthquake-news-video/final
          mkdir -p projects/earthquake-news-video/temp
          
          # Basic earthquake news script (placeholder)
          cat > projects/earthquake-news-video/temp/news-script.txt << 'EOF'
          最新の地震情報をお伝えします。
          
          本日、日本国内で地震が発生しました。
          震源地は詳細な調査により確認され、
          震度や規模について気象庁が発表しています。
          
          現在のところ、大きな被害の報告はありません。
          引き続き最新情報にご注意ください。
          
          以上、地震情報をお伝えしました。
          EOF
          
          echo "✅ 基本ニュース原稿を作成しました"
          
          # Create simple metadata
          cat > projects/earthquake-news-video/final/workflow-summary.json << EOF
          {
            "workflow": "earthquake-news-video-fallback",
            "status": "completed",
            "concept": "${{ inputs.concept }}",
            "region": "${{ inputs.earthquake_region }}",
            "generated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "deliverables": {
              "script": "projects/earthquake-news-video/temp/news-script.txt",
              "status": "basic template created"
            },
            "next_steps": [
              "Use full Meta Workflow for complete video generation",
              "Add specific earthquake data from reliable sources",
              "Implement image and video generation steps",
              "Add Japanese narration and subtitles"
            ]
          }
          EOF
          
          echo "✅ フォールバック版が正常に完了しました"
          echo "status=completed" >> $GITHUB_OUTPUT
          
          echo ""
          echo "📋 Summary:"
          echo "✅ Basic news script template created"
          echo "✅ Project structure initialized"
          echo "✅ Metadata generated"
          echo ""
          echo "🔄 Next steps:"
          echo "1. Fix YAML syntax issues in full Meta Workflow"
          echo "2. Re-run with corrected workflow for complete video generation"
          
  upload-deliverables:
    runs-on: ubuntu-latest
    needs: fallback-workflow
    if: needs.fallback-workflow.outputs.workflow_status == 'completed'
    
    steps:
      - name: Upload Fallback Results
        uses: actions/upload-artifact@v4
        with:
          name: earthquake-news-fallback-results
          path: projects/earthquake-news-video/
          retention-days: 7