name: "📺 Fixed Narrator News Video Workflow"

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "ニューストピック"
        required: true
        default: "最新のAI技術動向"
      narrator_seed:
        description: "ナレーターの固定seed値（同じ人物を維持）"
        required: false
        default: "japanese-female-announcer-2024"
      duration:
        description: "動画の長さ（秒）"
        required: false
        default: "60"

env:
  CLAUDE_CODE_CI_MODE: true
  CLAUDE_CODE_AUTO_APPROVE_MCP: true

jobs:
  # Phase 1: Setup and Generate Fixed Narrator
  setup-and-narrator:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    outputs:
      project_dir: ${{ steps.setup.outputs.project_dir }}
      narrator_image_path: ${{ steps.narrator.outputs.image_path }}
      scene_count: ${{ steps.calculate.outputs.scene_count }}
      scene_list: ${{ steps.calculate.outputs.scene_list }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project directory
        id: setup
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          PROJECT_DIR="projects/fixed-narrator-news-${TIMESTAMP}"
          mkdir -p "${PROJECT_DIR}"/{metadata,logs,media/{images,videos,audio},final,temp}
          echo "project_dir=${PROJECT_DIR}" >> $GITHUB_OUTPUT
          echo "✅ Project directory: ${PROJECT_DIR}"

      - name: Calculate scene count
        id: calculate
        run: |
          DURATION="${{ inputs.duration }}"
          SCENE_COUNT=$((DURATION / 5))
          echo "scene_count=${SCENE_COUNT}" >> $GITHUB_OUTPUT
          
          # Generate scene list
          SCENE_LIST="["
          for i in $(seq 1 $SCENE_COUNT); do
            [ $i -gt 1 ] && SCENE_LIST="${SCENE_LIST},"
            SCENE_LIST="${SCENE_LIST}${i}"
          done
          SCENE_LIST="${SCENE_LIST}]"
          echo "scene_list=${SCENE_LIST}" >> $GITHUB_OUTPUT
          echo "✅ Calculated ${SCENE_COUNT} scenes for ${DURATION} seconds"

      - name: Generate fixed Japanese female narrator
        id: narrator
        run: |
          PROJECT_DIR="${{ steps.setup.outputs.project_dir }}"
          SEED="${{ inputs.narrator_seed }}"
          
          # Generate consistent Japanese female news anchor
          NARRATOR_PROMPT="プロフェッショナルな日本人女性ニュースキャスターの画像を生成してください。

          重要な要件:
          - 年齢: 28-35歳の知的な日本人女性
          - 服装: ダークブルーまたはグレーのプロフェッショナルなジャケット
          - 髪型: 清潔感のあるショートボブまたはセミロング（黒髪）
          - 表情: 穏やかで信頼感のある微笑み
          - 背景: ニューススタジオ風（ぼかし気味）
          - ポーズ: 正面向き、カメラ目線
          - メイク: ナチュラルで品のあるメイク
          
          技術要件:
          - seed値: ${SEED}（一貫性のため固定）
          - 解像度: 1920x1080
          - スタイル: フォトリアリスティック、放送品質
          
          出力ファイル: japanese_female_narrator.png"

          npx @anthropic-ai/claude-code \
            --mcp-config ".claude/mcp-kamuicode.json" \
            --allowedTools "mcp__t2i-kamui-imagen3__imagen_t2i,Write" \
            --max-turns 20 \
            --permission-mode "acceptEdits" \
            -p "$NARRATOR_PROMPT"

          # Move to project directory
          if [ -f "japanese_female_narrator.png" ]; then
            mv japanese_female_narrator.png "$PROJECT_DIR/media/images/"
            echo "image_path=$PROJECT_DIR/media/images/japanese_female_narrator.png" >> $GITHUB_OUTPUT
            echo "✅ Fixed narrator image generated with seed: ${SEED}"
          else
            echo "❌ Failed to generate narrator image"
            exit 1
          fi

      - name: Upload narrator artifact
        uses: actions/upload-artifact@v4
        with:
          name: narrator-image
          path: ${{ steps.setup.outputs.project_dir }}/media/images/japanese_female_narrator.png

  # Phase 2: Information Gathering
  gather-information:
    runs-on: ubuntu-latest
    needs: setup-and-narrator
    timeout-minutes: 8
    outputs:
      script_path: ${{ steps.script.outputs.path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Research and create script
        id: script
        run: |
          PROJECT_DIR="${{ needs.setup-and-narrator.outputs.project_dir }}"
          TOPIC="${{ inputs.topic }}"
          SCENE_COUNT="${{ needs.setup-and-narrator.outputs.scene_count }}"
          
          RESEARCH_PROMPT="「${TOPIC}」について最新情報を調査し、${SCENE_COUNT}シーン構成の60秒ニュース原稿を作成してください。

          要件:
          1. WebSearchを使用して最新情報を収集
          2. 信頼できる複数の情報源から事実確認
          3. 各シーン5秒、計${SCENE_COUNT}シーンの構成
          4. 日本人女性アナウンサーが読み上げる自然な原稿
          
          出力形式:
          - news_script.json: シーンごとの原稿とビジュアル指示
          - narration_full.txt: 完全なナレーション原稿
          
          原稿のトーン:
          - プロフェッショナルで信頼感のある口調
          - 分かりやすく簡潔な表現
          - 視聴者に寄り添う温かみのある語り"

          npx @anthropic-ai/claude-code \
            --mcp-config ".claude/mcp-kamuicode.json" \
            --allowedTools "WebSearch,Write" \
            --max-turns 30 \
            --permission-mode "acceptEdits" \
            -p "$RESEARCH_PROMPT"

          # Move files to project
          mkdir -p "$PROJECT_DIR/metadata"
          [ -f "news_script.json" ] && mv news_script.json "$PROJECT_DIR/metadata/"
          [ -f "narration_full.txt" ] && mv narration_full.txt "$PROJECT_DIR/metadata/"
          
          echo "path=$PROJECT_DIR/metadata/news_script.json" >> $GITHUB_OUTPUT
          echo "✅ Script created for ${SCENE_COUNT} scenes"

      - name: Upload script artifact
        uses: actions/upload-artifact@v4
        with:
          name: news-script
          path: ${{ needs.setup-and-narrator.outputs.project_dir }}/metadata/

  # Phase 3: Generate Narration Audio
  generate-narration:
    runs-on: ubuntu-latest
    needs: [setup-and-narrator, gather-information]
    timeout-minutes: 8
    outputs:
      audio_path: ${{ steps.narration.outputs.path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download script
        uses: actions/download-artifact@v4
        with:
          name: news-script
          path: ${{ needs.setup-and-narrator.outputs.project_dir }}/metadata/

      - name: Generate narration audio
        id: narration
        run: |
          PROJECT_DIR="${{ needs.setup-and-narrator.outputs.project_dir }}"
          
          # Read narration text
          if [ -f "$PROJECT_DIR/metadata/narration_full.txt" ]; then
            NARRATION_TEXT=$(cat "$PROJECT_DIR/metadata/narration_full.txt")
          else
            NARRATION_TEXT="本日のニュースをお伝えします。${{ inputs.topic }}について、最新の情報をまとめました。"
          fi
          
          TTS_PROMPT="以下のテキストを日本人女性アナウンサーの声で読み上げてください。

          テキスト:
          ${NARRATION_TEXT}
          
          音声要件:
          - 声質: プロフェッショナルな女性アナウンサー（落ち着いた、信頼感のある声）
          - 速度: ニュース番組に適した標準的な速度
          - 抑揚: 重要部分での適切な強調
          - 全体の長さ: 60秒以内
          
          出力: narration_audio.mp3"

          npx @anthropic-ai/claude-code \
            --mcp-config ".claude/mcp-kamuicode.json" \
            --allowedTools "mcp__t2s-kamui-minimax-speech__minimax_speech_02_turbo_submit,mcp__t2s-kamui-minimax-speech__minimax_speech_02_turbo_status,mcp__t2s-kamui-minimax-speech__minimax_speech_02_turbo_result,Write" \
            --max-turns 40 \
            --permission-mode "acceptEdits" \
            -p "$TTS_PROMPT"

          # Move audio to project
          if [ -f "narration_audio.mp3" ]; then
            mv narration_audio.mp3 "$PROJECT_DIR/media/audio/"
            echo "path=$PROJECT_DIR/media/audio/narration_audio.mp3" >> $GITHUB_OUTPUT
            echo "✅ Narration audio generated"
          else
            echo "❌ Failed to generate narration audio"
          fi

      - name: Upload audio artifact
        uses: actions/upload-artifact@v4
        with:
          name: narration-audio
          path: ${{ needs.setup-and-narrator.outputs.project_dir }}/media/audio/

  # Phase 4: Generate Scene Videos with Lip-sync
  generate-scenes:
    runs-on: ubuntu-latest
    needs: [setup-and-narrator, gather-information, generate-narration]
    timeout-minutes: 20
    strategy:
      matrix:
        scene: ${{ fromJson(needs.setup-and-narrator.outputs.scene_list) }}
      max-parallel: 6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ needs.setup-and-narrator.outputs.project_dir }}/

      - name: Generate scene with lip-sync
        id: scene
        run: |
          PROJECT_DIR="${{ needs.setup-and-narrator.outputs.project_dir }}"
          SCENE_ID="${{ matrix.scene }}"
          NARRATOR_IMAGE="$PROJECT_DIR/narrator-image/japanese_female_narrator.png"
          AUDIO_FILE="$PROJECT_DIR/narration-audio/narration_audio.mp3"
          
          # Calculate time offsets for this scene
          START_TIME=$(( (SCENE_ID - 1) * 5 ))
          END_TIME=$(( SCENE_ID * 5 ))
          
          # Extract audio segment for this scene
          ffmpeg -i "$AUDIO_FILE" -ss ${START_TIME} -t 5 -acodec copy "$PROJECT_DIR/temp/scene_${SCENE_ID}_audio.mp3"
          
          SCENE_PROMPT="シーン${SCENE_ID}のリップシンク動画を生成してください。

          入力:
          - ナレーター画像: ${NARRATOR_IMAGE}
          - 音声セグメント: $PROJECT_DIR/temp/scene_${SCENE_ID}_audio.mp3
          - 時間: ${START_TIME}秒から${END_TIME}秒（5秒間）
          
          処理要件:
          1. 日本人女性ナレーターの画像を使用
          2. 音声に合わせた自然なリップシンク
          3. ニュースキャスター風の軽微な頭の動き
          4. 5秒の動画として出力
          
          使用ツール優先順位:
          1. mcp__v2v-kamui-pixverse-lipsync（推奨）
          2. mcp__v2v-kamui-creatify-lipsync（代替）
          
          出力: scene_${SCENE_ID}_lipsync.mp4"

          npx @anthropic-ai/claude-code \
            --mcp-config ".claude/mcp-kamuicode.json" \
            --allowedTools "mcp__v2v-kamui-pixverse-lipsync__pixverse_lipsync_submit,mcp__v2v-kamui-pixverse-lipsync__pixverse_lipsync_status,mcp__v2v-kamui-pixverse-lipsync__pixverse_lipsync_result,mcp__v2v-kamui-creatify-lipsync__lipsync_submit,mcp__v2v-kamui-creatify-lipsync__lipsync_status,mcp__v2v-kamui-creatify-lipsync__lipsync_result,Write,Read" \
            --max-turns 50 \
            --permission-mode "acceptEdits" \
            -p "$SCENE_PROMPT"

          # Move to project directory
          if [ -f "scene_${SCENE_ID}_lipsync.mp4" ]; then
            mv "scene_${SCENE_ID}_lipsync.mp4" "$PROJECT_DIR/media/videos/"
            echo "✅ Scene ${SCENE_ID} with lip-sync completed"
          else
            echo "⚠️ Scene ${SCENE_ID} generation failed, creating fallback"
            # Fallback: Create simple video from image
            ffmpeg -loop 1 -i "$NARRATOR_IMAGE" -i "$PROJECT_DIR/temp/scene_${SCENE_ID}_audio.mp3" \
              -c:v libx264 -c:a aac -shortest -t 5 \
              "$PROJECT_DIR/media/videos/scene_${SCENE_ID}_lipsync.mp4"
          fi

      - name: Upload scene artifact
        uses: actions/upload-artifact@v4
        with:
          name: scene-${{ matrix.scene }}
          path: ${{ needs.setup-and-narrator.outputs.project_dir }}/media/videos/scene_${{ matrix.scene }}_lipsync.mp4

  # Phase 5: Final Composition
  final-composition:
    runs-on: ubuntu-latest
    needs: [setup-and-narrator, generate-scenes]
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all scenes
        uses: actions/download-artifact@v4
        with:
          path: ${{ needs.setup-and-narrator.outputs.project_dir }}/

      - name: Compose final video
        run: |
          PROJECT_DIR="${{ needs.setup-and-narrator.outputs.project_dir }}"
          SCENE_COUNT="${{ needs.setup-and-narrator.outputs.scene_count }}"
          
          # Create scene list file for concatenation
          echo "# Scene list for concatenation" > "$PROJECT_DIR/temp/scene_list.txt"
          for i in $(seq 1 $SCENE_COUNT); do
            SCENE_FILE="$PROJECT_DIR/scene-${i}/scene_${i}_lipsync.mp4"
            if [ -f "$SCENE_FILE" ]; then
              echo "file '$SCENE_FILE'" >> "$PROJECT_DIR/temp/scene_list.txt"
            fi
          done
          
          # Concatenate all scenes
          ffmpeg -f concat -safe 0 -i "$PROJECT_DIR/temp/scene_list.txt" \
            -c:v libx264 -c:a aac -movflags +faststart \
            "$PROJECT_DIR/final/news_video_complete.mp4"
          
          # Add news overlay graphics (optional)
          OVERLAY_PROMPT="最終ニュース動画にテロップとグラフィックを追加してください。

          入力動画: $PROJECT_DIR/final/news_video_complete.mp4
          
          追加要素:
          1. ニュース番組風のロゴ（左上）
          2. トピックタイトル（下部テロップ）
          3. 時刻表示（右上）
          
          出力: news_video_final.mp4"

          npx @anthropic-ai/claude-code \
            --mcp-config ".claude/mcp-kamuicode.json" \
            --allowedTools "Read,Write,Bash" \
            --max-turns 20 \
            --permission-mode "acceptEdits" \
            -p "$OVERLAY_PROMPT"

          # Final check
          if [ -f "news_video_final.mp4" ]; then
            mv news_video_final.mp4 "$PROJECT_DIR/final/"
            echo "✅ Final news video created with fixed narrator"
          elif [ -f "$PROJECT_DIR/final/news_video_complete.mp4" ]; then
            echo "✅ Final news video created (without overlays)"
          else
            echo "❌ Failed to create final video"
            exit 1
          fi

      - name: Upload final video
        uses: actions/upload-artifact@v4
        with:
          name: final-news-video
          path: ${{ needs.setup-and-narrator.outputs.project_dir }}/final/

      - name: Create summary
        run: |
          PROJECT_DIR="${{ needs.setup-and-narrator.outputs.project_dir }}"
          
          echo "# 📺 Fixed Narrator News Video Generation Complete" > "$PROJECT_DIR/final/summary.md"
          echo "" >> "$PROJECT_DIR/final/summary.md"
          echo "## Details:" >> "$PROJECT_DIR/final/summary.md"
          echo "- Topic: ${{ inputs.topic }}" >> "$PROJECT_DIR/final/summary.md"
          echo "- Duration: ${{ inputs.duration }} seconds" >> "$PROJECT_DIR/final/summary.md"
          echo "- Narrator: Japanese female announcer (fixed)" >> "$PROJECT_DIR/final/summary.md"
          echo "- Scenes: ${{ needs.setup-and-narrator.outputs.scene_count }}" >> "$PROJECT_DIR/final/summary.md"
          echo "- Timestamp: $(date)" >> "$PROJECT_DIR/final/summary.md"
          echo "" >> "$PROJECT_DIR/final/summary.md"
          echo "## Output Files:" >> "$PROJECT_DIR/final/summary.md"
          ls -la "$PROJECT_DIR/final/" >> "$PROJECT_DIR/final/summary.md"
          
          cat "$PROJECT_DIR/final/summary.md"