name: module-audio-generation-kc-multi-model-ccsdk

on:
  workflow_call:
    inputs:
      concept:
        description: 'ユーザーのコンセプト'
        required: true
        type: string
      model-type:
        description: '使用する音声生成モデル (例: t2s-fal-minimax-speech-02-turbo)'
        required: true
        type: string
      text-prompt:
        description: '音声生成用テキストプロンプト'
        required: true
        type: string
      voice-settings:
        description: '音声設定（JSON形式、オプション）'
        required: false
        type: string
        default: '{}'
      branch-name:
        description: 'ワーキングブランチ名'
        required: true
        type: string
      folder-name:
        description: 'プロジェクトフォルダ名'
        required: true
        type: string
      audio_index:
        description: '音声インデックス'
        required: false
        type: string
        default: '1'
    outputs:
      completed:
        description: '完了ステータス'
        value: ${{ jobs.audio-generation.outputs.completed }}
      audio-url:
        description: '音声URL'
        value: ${{ jobs.audio-generation.outputs.audio-url }}
    secrets:
      anthropic_api_key:
        description: 'Anthropic API Key'
        required: true
      github_pat:
        description: 'GitHub Token'
        required: true

jobs:
  audio-generation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      completed: ${{ steps.audio.outputs.completed }}
      audio-url: ${{ steps.audio.outputs.audio-url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Claude Code SDK
        run: npm install @anthropic-ai/claude-code
      
      - name: Install ffmpeg for audio duration check
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: 音声生成エージェント (マルチモデル対応)
        id: audio
        env:
          ANTHROPIC_API_KEY: ${{ secrets.anthropic_api_key }}
        run: |
          echo "::group::🎤 Audio Generation Agent Execution (Multi-Model)"
          echo "Starting at: $(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)"
          
          # 設定
          USER_CONCEPT="${{ inputs.concept }}"
          MODEL_TYPE="${{ inputs.model-type }}"
          TEXT_PROMPT="${{ inputs.text-prompt }}"
          VOICE_SETTINGS="${{ inputs.voice-settings }}"
          FOLDER_NAME="${{ inputs.folder-name }}"
          AUDIO_INDEX="${{ inputs.audio_index }}"
          AUDIO_DIR="$FOLDER_NAME/audio-${AUDIO_INDEX}"
          
          echo "User concept: $USER_CONCEPT"
          echo "Model type: $MODEL_TYPE"
          echo "Text prompt: $TEXT_PROMPT"
          echo "Voice settings: $VOICE_SETTINGS"
          echo "Audio index: $AUDIO_INDEX"
          echo "Target folder: $AUDIO_DIR"
          
          # 音声フォルダを事前に作成
          if [ ! -d "$AUDIO_DIR" ]; then
            mkdir -p "$AUDIO_DIR"
            echo "📁 Created audio folder: $AUDIO_DIR"
          fi
          
          # MCP設定の確認
          MCP_CONFIG_PATH=".claude/mcp-kamuicode.json"
          MCP_CONFIG_ABS_PATH="$(pwd)/$MCP_CONFIG_PATH"
          
          # MCP設定ファイルの存在確認
          if [ -f "$MCP_CONFIG_ABS_PATH" ]; then
            echo "✅ MCP config file exists at: $MCP_CONFIG_ABS_PATH"
          else
            echo "❌ MCP config file not found at: $MCP_CONFIG_ABS_PATH"
            exit 1
          fi
          
          # プロンプトの構築
          PROMPT="指定されたモデルタイプを使用して音声を生成してください。

          **元のユーザー指示**: $USER_CONCEPT
          **使用するモデルタイプ**: $MODEL_TYPE
          **テキストプロンプト**: $TEXT_PROMPT
          **音声設定**: $VOICE_SETTINGS

          **実行手順**:
          1. まず、\`.github/workflows/kamuicode/kamuicode-usage.md\`ファイルを読み込んで、モデルタイプ「$MODEL_TYPE」に対応するMCPツール名を確認してください
          2. ファイルから以下の情報を抽出:
             - submitツール名（例: mcp__t2s-fal-minimax-speech-02-turbo__minimax_speech_02_turbo_submit）
             - statusツール名（例: mcp__t2s-fal-minimax-speech-02-turbo__minimax_speech_02_turbo_status）
             - resultツール名（例: mcp__t2s-fal-minimax-speech-02-turbo__minimax_speech_02_turbo_result）
          3. モデルタイプに応じて適切なパラメータを使用:
             - **t2s-で始まる場合**: テキストプロンプト（$TEXT_PROMPT）と音声設定（$VOICE_SETTINGS）を使用してテキストから音声生成
          4. submitツールで音声生成を開始
          5. statusツールでステータス確認（音声生成は比較的高速ですが、適度な間隔で確認）
          6. 必要に応じてBashツールで \`sleep 30\` を実行してから再度ステータス確認
          7. resultツールで結果取得して音声URLを取得
          8. **必須**: 取得した音声URLを「$AUDIO_DIR/audio-url.txt」ファイルに保存
          9. **必須**: 取得した音声URLをBashツールで「$AUDIO_DIR/audio.mp3」または「$AUDIO_DIR/audio.wav」にダウンロード保存

          **重要な注意点**:
          - kamuicode-usage.mdから正しいツール名を読み取ること
          - 音声生成は比較的高速ですが、ステータス確認は適度な間隔で行うこと
          - Google URLの有効期限は約1時間のため、生成後すぐにダウンロード
          - 必ずGoogle提供の認証済URLを使用
          - 音声は必ず「$AUDIO_DIR」ディレクトリに保存
          - ファイル名は「audio.mp3」または「audio.wav」とする
          - **最重要**: 生成時の音声URLを「$AUDIO_DIR/audio-url.txt」に保存し、次のジョブで参照できるようにする
          - **両方を実行**: ①音声URLをテキストファイルに保存 ②音声URLから音声をダウンロードしてローカル保存"
          
          echo "🚀 Starting Audio Generation Agent Claude Code CLI..."
          echo "📝 Prompt length: ${#PROMPT}"
          
          # Claude Code CLIの実行（音声生成系ツールはワイルドカードで許可）
          npx @anthropic-ai/claude-code \
            --mcp-config="$MCP_CONFIG_ABS_PATH" \
            --allowedTools "mcp__t2s-*,Read,Bash" \
            --max-turns 40 \
            --verbose \
            --permission-mode "acceptEdits" \
            -p "$PROMPT" || {
              echo "::error::❌ Claude Code CLI execution failed"
              exit 1
            }
          
          # 生成された音声の確認
          echo ""
          echo "🎤 Checking generated audio..."
          if [ -d "$AUDIO_DIR" ]; then
            AUDIO_COUNT=$(find "$AUDIO_DIR" -name "*.mp3" -o -name "*.wav" -o -name "*.m4a" | wc -l)
            echo "::notice::🎤 Generated $AUDIO_COUNT audio files using $MODEL_TYPE"
            if [ "$AUDIO_COUNT" -gt 0 ]; then
              # 音声ファイルサイズと長さの確認（Pixverse制限: 30秒以内）
              for audio_file in $(find "$AUDIO_DIR" -name "*.mp3" -o -name "*.wav" -o -name "*.m4a" | head -3); do
                if [ -f "$audio_file" ]; then
                  AUDIO_SIZE=$(stat -c%s "$audio_file" 2>/dev/null || stat -f%z "$audio_file" 2>/dev/null || echo "0")
                  echo "::notice::🎵 Audio file: $audio_file (${AUDIO_SIZE} bytes)"
                  
                  if [ "$AUDIO_SIZE" -eq 0 ]; then
                    echo "::error::❌ Audio file is empty: $audio_file"
                    exit 1
                  fi
                  
                  # Pixverse制限チェック（30秒以内）
                  # ffprobeで音声の長さを取得
                  if command -v ffprobe >/dev/null 2>&1; then
                    AUDIO_DURATION=$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "$audio_file" 2>/dev/null || echo "0")
                    AUDIO_DURATION_INT=$(echo "$AUDIO_DURATION" | cut -d. -f1)
                    echo "::notice::⏱️ Audio duration: ${AUDIO_DURATION}s"
                    
                    if [ "$AUDIO_DURATION_INT" -gt 30 ]; then
                      echo "::warning::⚠️ Audio file exceeds Pixverse 30s limit: $audio_file (${AUDIO_DURATION}s)"
                      echo "::warning::💡 Audio may not be compatible with Pixverse lipsync but continuing workflow"
                    else
                      echo "::notice::✅ Audio file is within Pixverse 30s limit: ${AUDIO_DURATION}s"
                    fi
                  else
                    echo "::warning::⚠️ ffprobe not available, skipping audio duration check"
                  fi
                fi
              done
              
              # 音声URLファイルの確認と出力設定
              AUDIO_URL_FILE="$AUDIO_DIR/audio-url.txt"
              if [ -f "$AUDIO_URL_FILE" ]; then
                AUDIO_URL=$(cat "$AUDIO_URL_FILE")
                echo "✅ Audio URL found: $AUDIO_URL"
                echo "audio-url=$AUDIO_URL" >> $GITHUB_OUTPUT
              else
                echo "❌ Audio URL file not found: $AUDIO_URL_FILE"
                echo "Creating empty URL file to continue workflow..."
                echo "" > "$AUDIO_URL_FILE"
                echo "audio-url=" >> $GITHUB_OUTPUT
              fi
            else
              echo "::error::❌ No audio files were generated"
              exit 1
            fi
          else
            echo "::error::❌ Audio directory not found"
            exit 1
          fi
          
          echo "completed=true" >> $GITHUB_OUTPUT
          echo "::endgroup::"
      
      - name: Commit and push audio
        env:
          GH_TOKEN: ${{ secrets.github_pat }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ inputs.folder-name }}/
          if git diff --cached --quiet; then
            echo "No audio files to commit"
          else
            git commit -m "Add generated audio using ${{ inputs.model-type }}: ${{ inputs.concept }}
            
            🤖 Generated with [Claude Code](https://claude.ai/code)
            
            Co-Authored-By: Claude <noreply@anthropic.com>"
            # 並列実行での競合を回避するためのリトライ処理
            for i in {1..3}; do
              git pull --rebase origin ${{ inputs.branch-name }} || true
              if git push origin ${{ inputs.branch-name }}; then
                echo "✅ Push successful on attempt $i"
                break
              else
                echo "⚠️ Push failed on attempt $i, retrying..."
                # ランダムな待機時間（1-5秒）
                sleep $((RANDOM % 5 + 1))
              fi
            done
          fi