name: Emergency Auto-Fix System
run-name: 🚨 Emergency response - Auto-fixing critical workflow failures

on:
  workflow_run:
    workflows: ["Kamuicode Meta Generator (Self-Healing)"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_analysis:
        description: '強制的に分析を実行'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write
  actions: write
  issues: write

env:
  CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

jobs:
  # 失敗判定・早期終了
  check-failure:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure')
    outputs:
      should_proceed: ${{ steps.check.outputs.should_proceed }}
    
    steps:
      - name: Check if Auto-Fix is Needed
        id: check
        run: |
          echo "🔍 Checking workflow status..."
          echo "Event: ${{ github.event_name }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion || 'N/A' }}"
          
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "🔧 Manual trigger - proceeding with auto-fix"
            echo "should_proceed=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "workflow_run" ] && [ "${{ github.event.workflow_run.conclusion }}" == "failure" ]; then
            echo "❌ Workflow failure detected - proceeding with auto-fix"
            echo "should_proceed=true" >> $GITHUB_OUTPUT
          else
            echo "✅ Workflow completed successfully - no auto-fix needed"
            echo "Conclusion: ${{ github.event.workflow_run.conclusion || 'N/A' }}"
            echo "should_proceed=false" >> $GITHUB_OUTPUT
          fi

  # 簡素化された自動修正
  auto-fix:
    needs: check-failure
    runs-on: ubuntu-latest
    if: needs.check-failure.outputs.should_proceed == 'true'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Apply Basic Auto-Fixes
        run: |
          echo "🔧 Applying basic auto-fixes..."
          
          mkdir -p .meta/auto-fix
          
          # 基本的な修正処理
          FIXES_APPLIED=""
          
          # Fix 1: ディレクトリ構造の確保
          mkdir -p .meta/{diagnostics,tasks,generated,logs} generated/{config,prompts,scripts}
          FIXES_APPLIED="${FIXES_APPLIED}directories-created;"
          
          # Fix 2: MCP設定確認（簡素化）
          if [ -f "mcp-kamuicode.json" ]; then
            mkdir -p ~/.claude
            cp mcp-kamuicode.json ~/.claude/mcp-kamuicode.json 2>/dev/null || true
            FIXES_APPLIED="${FIXES_APPLIED}mcp-config-checked;"
          fi
          
          # 修正記録
          cat > .meta/auto-fix/fix-summary-$(date +%Y%m%d-%H%M%S).json << EOF
          {
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "fixes_applied": "$FIXES_APPLIED",
            "trigger": "${{ github.event_name }}",
            "workflow_conclusion": "${{ github.event.workflow_run.conclusion || 'manual' }}"
          }
          EOF
          
          echo "✅ Basic auto-fixes completed: $FIXES_APPLIED"
          
      - name: Commit Fixes
        run: |
          git config user.name "auto-fix-bot[bot]"
          git config user.email "auto-fix-bot[bot]@users.noreply.github.com"
          
          git add .meta/auto-fix/
          
          if ! git diff --cached --quiet; then
            git commit -m "fix: Auto-fix system repairs

            Applied basic system repairs and validations.
            
            🤖 Generated with [Claude Code](https://claude.ai/code)
            Co-Authored-By: Claude <noreply@anthropic.com>"
            
            git push origin main || echo "Push failed, but continuing..."
            echo "✅ Auto-fixes committed"
          else
            echo "ℹ️ No changes to commit"
          fi