name: dynamic-multimedia-generation
'on':
  workflow_dispatch:
    inputs:
      user_prompt:
        description: User requirements for multimedia generation
        required: true
        type: string
        default: テキストから画像生成 | 画像から動画生成 | テキストから音楽生成 | 動画から音声抽出
  issues:
    types:
    - opened
    - edited
permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write
env:
  WORKFLOW_TYPE: dynamic-multimedia
  GENERATED_AT: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
  REQUIREMENTS: テキストから画像生成 | 画像から動画生成 | テキストから音楽生成 | 動画から音声抽出
jobs:
  stage_1:
    runs-on: ubuntu-latest
    timeout-minutes: 167
    env:
      STAGE: '1'
      TASK_NODE_IDS: image-generation_0_50,news-summarization_0_68,blog-article-creation_0_33,image-generation_0_43,audio-music-creation_0_8,presentation-slide-creation_0_81,news-summarization_0_77,blog-article-creation_0_21,3d-model-creation_0_0,audio-music-creation_0_16,image-generation_0_45,image-generation_0_49,video-content-creation_0_90,video-content-creation_0_94,image-generation_0_51,presentation-slide-creation_0_84,video-content-creation_0_91,3d-model-creation_0_2,image-generation_0_48,presentation-slide-creation_0_87,video-content-creation_0_96,presentation-slide-creation_0_85,multimedia-ad-campaign_0_60,multimedia-ad-campaign_0_62,video-content-creation_0_97,data-analysis-visualization_0_39,audio-music-creation_0_12,video-content-creation_0_93,3d-model-creation_0_3,video-content-creation_0_95,multimedia-ad-campaign_0_61
      TASK_COUNT: 31
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Multi-Task Environment
      run: "\n                        echo \"\U0001F527 Setting up multi-task environment\
        \ for stage 1...\"\n                        mkdir -p .logs outputs artifacts\n\
        \                        echo \"Processing 31 tasks in sequence...\"\n   \
        \                     echo \"STAGE_START_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)\"\
        \ >> $GITHUB_ENV\n                    "
    - name: 'Execute: 画像メタデータ抽出'
      run: "\n                    echo \"\U0001F4DD Starting task: 画像メタデータ抽出\"\n \
        \                   echo \"CURRENT_TASK=image-generation_0_50\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: 分析対象トピック・キーワード抽出'
      run: "\n                    echo \"\U0001F4DD Starting task: 分析対象トピック・キーワード抽出\"\
        \n                    echo \"CURRENT_TASK=news-summarization_0_68\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: メタデータ・SNS用データ生成'
      run: "\n                    echo \"\U0001F4DD Starting task: メタデータ・SNS用データ生成\"\
        \n                    echo \"CURRENT_TASK=blog-article-creation_0_33\" >>\
        \ $GITHUB_ENV\n                "
    - name: 'Execute: 画像生成用MCP・API接続テスト'
      run: "\n                    echo \"\U0001F4DD Starting task: 画像生成用MCP・API接続テスト\"\
        \n                    echo \"CURRENT_TASK=image-generation_0_43\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: 音声・音楽生成サービス接続テスト'
      run: "\n                    echo \"\U0001F4DD Starting task: 音声・音楽生成サービス接続テスト\"\
        \n                    echo \"CURRENT_TASK=audio-music-creation_0_8\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: デザイン・生成サービス接続テスト'
      run: "\n                    echo \"\U0001F4DD Starting task: デザイン・生成サービス接続テスト\"\
        \n                    echo \"CURRENT_TASK=presentation-slide-creation_0_81\"\
        \ >> $GITHUB_ENV\n                "
    - name: 'Execute: エグゼクティブサマリー生成'
      run: "\n                    echo \"\U0001F4DD Starting task: エグゼクティブサマリー生成\"\
        \n                    echo \"CURRENT_TASK=news-summarization_0_77\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: ユーザーの疑問・質問の抽出'
      run: "\n                    echo \"\U0001F4DD Starting task: ユーザーの疑問・質問の抽出\"\
        \n                    echo \"CURRENT_TASK=blog-article-creation_0_21\" >>\
        \ $GITHUB_ENV\n                "
    - name: 'Execute: 3D生成・処理サービス接続テスト'
      run: "\n                    echo \"\U0001F4DD Starting task: 3D生成・処理サービス接続テスト\"\
        \n                    echo \"CURRENT_TASK=3d-model-creation_0_0\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: 最終オーディオパッケージ作成'
      run: "\n                    echo \"\U0001F4DD Starting task: 最終オーディオパッケージ作成\"\
        \n                    echo \"CURRENT_TASK=audio-music-creation_0_16\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: ビジュアルコンセプトの計画'
      run: "\n                    echo \"\U0001F4DD Starting task: ビジュアルコンセプトの計画\"\
        \n                    echo \"CURRENT_TASK=image-generation_0_45\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: 画像品質分析'
      run: "\n                    echo \"\U0001F4DD Starting task: 画像品質分析\"\n    \
        \                echo \"CURRENT_TASK=image-generation_0_49\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: メディア生成サービス接続テスト'
      run: "\n                    echo \"\U0001F4DD Starting task: メディア生成サービス接続テスト\"\
        \n                    echo \"CURRENT_TASK=video-content-creation_0_90\" >>\
        \ $GITHUB_ENV\n                "
    - name: 'Execute: ビジュアル一貫性チェック・調整'
      run: "\n                    echo \"\U0001F4DD Starting task: ビジュアル一貫性チェック・調整\"\
        \n                    echo \"CURRENT_TASK=video-content-creation_0_94\" >>\
        \ $GITHUB_ENV\n                "
    - name: 'Execute: 画像の精細化・改善'
      run: "\n                    echo \"\U0001F4DD Starting task: 画像の精細化・改善\"\n \
        \                   echo \"CURRENT_TASK=image-generation_0_51\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: ビジュアルデザイン企画・テンプレート設計'
      run: "\n                    echo \"\U0001F4DD Starting task: ビジュアルデザイン企画・テンプレート設計\"\
        \n                    echo \"CURRENT_TASK=presentation-slide-creation_0_84\"\
        \ >> $GITHUB_ENV\n                "
    - name: 'Execute: 動画コンセプト・企画立案'
      run: "\n                    echo \"\U0001F4DD Starting task: 動画コンセプト・企画立案\"\n\
        \                    echo \"CURRENT_TASK=video-content-creation_0_91\" >>\
        \ $GITHUB_ENV\n                "
    - name: 'Execute: 参照画像生成・前処理'
      run: "\n                    echo \"\U0001F4DD Starting task: 参照画像生成・前処理\"\n\
        \                    echo \"CURRENT_TASK=3d-model-creation_0_2\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: 初回画像生成'
      run: "\n                    echo \"\U0001F4DD Starting task: 初回画像生成\"\n    \
        \                echo \"CURRENT_TASK=image-generation_0_48\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: ビジュアル・コンテンツ統合'
      run: "\n                    echo \"\U0001F4DD Starting task: ビジュアル・コンテンツ統合\"\
        \n                    echo \"CURRENT_TASK=presentation-slide-creation_0_87\"\
        \ >> $GITHUB_ENV\n                "
    - name: 'Execute: BGM・効果音生成'
      run: "\n                    echo \"\U0001F4DD Starting task: BGM・効果音生成\"\n \
        \                   echo \"CURRENT_TASK=video-content-creation_0_96\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: スライド背景・グラフィック生成'
      run: "\n                    echo \"\U0001F4DD Starting task: スライド背景・グラフィック生成\"\
        \n                    echo \"CURRENT_TASK=presentation-slide-creation_0_85\"\
        \ >> $GITHUB_ENV\n                "
    - name: 'Execute: メインビジュアル・ヒーロー画像制作'
      run: "\n                    echo \"\U0001F4DD Starting task: メインビジュアル・ヒーロー画像制作\"\
        \n                    echo \"CURRENT_TASK=multimedia-ad-campaign_0_60\" >>\
        \ $GITHUB_ENV\n                "
    - name: 'Execute: BGM・効果音・音声素材制作'
      run: "\n                    echo \"\U0001F4DD Starting task: BGM・効果音・音声素材制作\"\
        \n                    echo \"CURRENT_TASK=multimedia-ad-campaign_0_62\" >>\
        \ $GITHUB_ENV\n                "
    - name: 'Execute: 動画品質向上・最終調整'
      run: "\n                    echo \"\U0001F4DD Starting task: 動画品質向上・最終調整\"\n\
        \                    echo \"CURRENT_TASK=video-content-creation_0_97\" >>\
        \ $GITHUB_ENV\n                "
    - name: 'Execute: 分析モデリング・洞察抽出'
      run: "\n                    echo \"\U0001F4DD Starting task: 分析モデリング・洞察抽出\"\n\
        \                    echo \"CURRENT_TASK=data-analysis-visualization_0_39\"\
        \ >> $GITHUB_ENV\n                "
    - name: 'Execute: メイン楽曲生成'
      run: "\n                    echo \"\U0001F4DD Starting task: メイン楽曲生成\"\n   \
        \                 echo \"CURRENT_TASK=audio-music-creation_0_12\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: キーフレーム画像生成'
      run: "\n                    echo \"\U0001F4DD Starting task: キーフレーム画像生成\"\n\
        \                    echo \"CURRENT_TASK=video-content-creation_0_93\" >>\
        \ $GITHUB_ENV\n                "
    - name: 'Execute: メイン3Dモデル生成'
      run: "\n                    echo \"\U0001F4DD Starting task: メイン3Dモデル生成\"\n\
        \                    echo \"CURRENT_TASK=3d-model-creation_0_3\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: メイン動画生成'
      run: "\n                    echo \"\U0001F4DD Starting task: メイン動画生成\"\n   \
        \                 echo \"CURRENT_TASK=video-content-creation_0_95\" >> $GITHUB_ENV\n\
        \                "
    - name: 'Execute: 動画コンテンツ・アニメーション制作'
      run: "\n                    echo \"\U0001F4DD Starting task: 動画コンテンツ・アニメーション制作\"\
        \n                    echo \"CURRENT_TASK=multimedia-ad-campaign_0_61\" >>\
        \ $GITHUB_ENV\n                "
    - name: Upload stage results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: stage-1-results
        path: outputs/
        retention-days: 7
  autofix_integration:
    needs: []
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Trigger AutoFix
      run: "\n                        echo \"\U0001F527 Triggering AutoFix system...\"\
        \n                        # AutoFix システムへの通知\n                        echo\
        \ \"AUTOFIX_TRIGGERED=true\" >> $GITHUB_ENV\n                    "
  monitor_integration:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Report to Monitor
      run: "\n                        echo \"\U0001F4CA Reporting to Monitor system...\"\
        \n                        echo \"MONITOR_REPORTED=true\" >> $GITHUB_ENV\n\
        \                    "
