name: Kamuicode Meta Generator (Self-Healing)
run-name: ${{ github.actor }} generates workflow for "${{ github.event.issue.title || github.event.inputs.description }}" 🤖🔄

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:
    inputs:
      workflow_type:
        description: 'ワークフローのタイプ'
        required: true
        type: choice
        options:
          - image-generation
          - video-generation
          - audio-generation
          - news-article
          - news-video
          - social-integration
          - custom
      description:
        description: '生成したいワークフローの説明'
        required: true
        type: string
      retry_mode:
        description: '失敗したワークフローのリトライ'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

env:
  CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

jobs:
  # Step 0: 自己診断・環境準備
  self-diagnostic:
    runs-on: ubuntu-latest
    outputs:
      diagnostic_result: ${{ steps.diagnose.outputs.result }}
      fixes_applied: ${{ steps.diagnose.outputs.fixes_applied }}
      retry_count: ${{ steps.diagnose.outputs.retry_count }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Self-Diagnostic & Auto-Fix
        id: diagnose
        run: |
          echo "🔍 Starting self-diagnostic..."
          
          # 診断結果とログを保存するディレクトリ作成
          mkdir -p .meta/diagnostics .meta/fixes
          
          # 失敗履歴の確認
          RETRY_COUNT=0
          if [ -f ".meta/diagnostics/retry_count" ]; then
            RETRY_COUNT=$(cat .meta/diagnostics/retry_count)
          fi
          
          # リトライ回数の更新
          echo $((RETRY_COUNT + 1)) > .meta/diagnostics/retry_count
          
          FIXES_APPLIED=""
          
          # Fix 1: MCP設定ファイルの自動作成（AI生成サービス用のみ）
          echo "🔧 Creating MCP configuration for AI generation services..."
          mkdir -p ~/.claude
          
          # ワークフロータイプを確認してMCPが必要かチェック
          WORKFLOW_TYPE="${{ github.event.inputs.workflow_type || 'unknown' }}"
          
          if [[ "$WORKFLOW_TYPE" =~ ^(image-generation|video-generation|audio-generation|news-video)$ ]]; then
            cat > ~/.claude/mcp-kamuicode.json << 'EOF'
          {
            "mcpServers": {
              "t2i-google-imagen3": {
                "type": "http",
                "url": "https://mcp-hunyuan3d-fix-20250711-022649-9904c5ca-zl3xx5lsaq-uc.a.run.app/t2i/google/imagen",
                "description": "Google Imagen 3 Text-to-Image Generation"
              },
              "t2v-fal-veo3-fast": {
                "type": "http",
                "url": "https://mcp-hunyuan3d-fix-20250711-022649-9904c5ca-zl3xx5lsaq-uc.a.run.app/t2v/fal/veo3/fast",
                "description": "Fal.ai Veo3 Fast Text-to-Video Generation P+"
              },
              "t2m-google-lyria": {
                "type": "http",
                "url": "https://mcp-hunyuan3d-fix-20250711-022649-9904c5ca-zl3xx5lsaq-uc.a.run.app/t2m/google/lyria",
                "description": "Google Lyria Text-to-Music Generation P+"
              }
            }
          }
          EOF
            FIXES_APPLIED="${FIXES_APPLIED}mcp-config-created-for-ai-generation;"
            echo "✅ MCP configuration created for AI generation services"
          else
            echo "ℹ️ MCP not needed for text-only workflow type: $WORKFLOW_TYPE"
            FIXES_APPLIED="${FIXES_APPLIED}mcp-not-required;"
          fi
          
          # Fix 2: 必要なディレクトリ構造の確認・作成
          echo "🔧 Ensuring directory structure..."
          mkdir -p .meta/{requests,tasks,generated,logs} generated/{config,prompts,scripts}
          FIXES_APPLIED="${FIXES_APPLIED}directories-created;"
          
          # Fix 3: プロンプトファイルの存在確認
          echo "🔧 Checking prompt files..."
          if [ ! -f "meta/prompts/task-decomposition.md" ]; then
            echo "⚠️ Missing task-decomposition.md - will use fallback"
            FIXES_APPLIED="${FIXES_APPLIED}missing-prompts-detected;"
          fi
          
          # 診断結果の保存
          cat > .meta/diagnostics/diagnostic-$(date +%Y%m%d-%H%M%S).json << EOF
          {
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "retry_count": $((RETRY_COUNT + 1)),
            "fixes_applied": "$FIXES_APPLIED",
            "environment": {
              "runner_os": "$RUNNER_OS",
              "github_event": "${{ github.event_name }}",
              "claude_token_present": "${{ secrets.CLAUDE_CODE_OAUTH_TOKEN != '' }}"
            }
          }
          EOF
          
          echo "result=success" >> $GITHUB_OUTPUT
          echo "fixes_applied=$FIXES_APPLIED" >> $GITHUB_OUTPUT
          echo "retry_count=$((RETRY_COUNT + 1))" >> $GITHUB_OUTPUT
          
          echo "🎯 Self-diagnostic completed. Fixes applied: $FIXES_APPLIED"
          
      - name: Upload Diagnostic Data
        uses: actions/upload-artifact@v4
        with:
          name: diagnostic-${{ github.run_number }}
          path: .meta/diagnostics/
          retention-days: 30

  # Step 1: 要求の初期分析（エラーハンドリング強化）
  analyze-request:
    needs: self-diagnostic
    runs-on: ubuntu-latest
    outputs:
      workflow_type: ${{ steps.analyze.outputs.workflow_type }}
      branch_name: ${{ steps.analyze.outputs.branch_name }}
      request_file: ${{ steps.analyze.outputs.request_file }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Analyze Request with Error Handling
        id: analyze
        run: |
          set -e  # エラー時に即座に終了
          
          echo "📋 Starting request analysis..."
          
          # 要求の分析と保存
          mkdir -p .meta/requests
          
          if [ "${{ github.event_name }}" == "issues" ]; then
            TITLE="${{ github.event.issue.title }}"
            BODY="${{ github.event.issue.body }}"
            REQUEST_ID="issue-${{ github.event.issue.number }}"
          else
            TITLE="${{ github.event.inputs.description }}"
            BODY="${{ github.event.inputs.description }}"
            REQUEST_ID="manual-$(date +%Y%m%d-%H%M%S)"
          fi
          
          # 入力検証
          if [ -z "$TITLE" ] || [ -z "$BODY" ]; then
            echo "❌ Error: Empty title or body"
            exit 1
          fi
          
          # ワークフロータイプの推定（改良版）
          if echo "$TITLE $BODY" | grep -qi "画像\|image\|バナー\|ロゴ\|illustration"; then
            WORKFLOW_TYPE="image-generation"
          elif echo "$TITLE $BODY" | grep -qi "動画\|video\|アニメーション\|movie\|clip"; then
            WORKFLOW_TYPE="video-generation"
          elif echo "$TITLE $BODY" | grep -qi "音声\|audio\|ナレーション\|music\|sound"; then
            WORKFLOW_TYPE="audio-generation"
          elif echo "$TITLE $BODY" | grep -qi "ニュース.*動画\|news.*video"; then
            WORKFLOW_TYPE="news-video"
          elif echo "$TITLE $BODY" | grep -qi "ニュース\|記事\|article\|news"; then
            WORKFLOW_TYPE="news-article"
          elif echo "$TITLE $BODY" | grep -qi "sns\|social\|twitter\|instagram"; then
            WORKFLOW_TYPE="social-integration"
          else
            WORKFLOW_TYPE="custom"
          fi
          
          # ブランチ名の生成
          SAFE_TITLE=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//' | cut -c1-50)
          BRANCH_NAME="workflow/${WORKFLOW_TYPE}-${REQUEST_ID}"
          
          # 要求をファイルに保存
          cat > .meta/requests/${REQUEST_ID}.md << EOF
          # Workflow Generation Request
          
          ## Type: ${WORKFLOW_TYPE}
          ## Title: ${TITLE}
          
          ## Description:
          ${BODY}
          
          ## Metadata:
          - Request ID: ${REQUEST_ID}
          - Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)
          - Source: ${{ github.event_name }}
          - Retry Count: ${{ needs.self-diagnostic.outputs.retry_count }}
          - Applied Fixes: ${{ needs.self-diagnostic.outputs.fixes_applied }}
          EOF
          
          echo "workflow_type=$WORKFLOW_TYPE" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "request_file=.meta/requests/${REQUEST_ID}.md" >> $GITHUB_OUTPUT
          
          echo "✅ Request analysis completed: Type=$WORKFLOW_TYPE"
          
      - name: Upload Request Artifact
        uses: actions/upload-artifact@v4
        with:
          name: request-${{ github.run_number }}
          path: .meta/requests/
          retention-days: 30

  # Step 2: タスク分解（自己修復機能付き）
  decompose-tasks:
    needs: [self-diagnostic, analyze-request]
    runs-on: ubuntu-latest
    outputs:
      task_count: ${{ steps.decompose.outputs.task_count }}
      complexity: ${{ steps.decompose.outputs.complexity }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download Request
        uses: actions/download-artifact@v4
        with:
          name: request-${{ github.run_number }}
          path: .meta/requests/
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code
        
      - name: Setup Claude Code Environment
        run: |
          echo "🔧 Setting up Claude Code for direct text generation..."
          # MCPは不要 - Claude Code GitHub Actionsで直接テキスト生成を実行
          
      - name: Decompose Tasks with Fallback
        id: decompose
        run: |
          set -e
          
          echo "🔄 Starting task decomposition..."
          
          # プロンプトファイルの確認と代替処理
          PROMPT_FILE="meta/prompts/task-decomposition.md"
          
          if [ ! -f "$PROMPT_FILE" ]; then
            echo "⚠️ Prompt file not found, creating fallback..."
            mkdir -p meta/prompts
            cat > "$PROMPT_FILE" << 'EOF'
          # Task Decomposition Prompt (Fallback)
          
          Please decompose the user request into executable tasks and save as .meta/tasks/task-plan.json:
          
          ```json
          {
            "complexity_level": 2,
            "estimated_duration_minutes": 30,
            "tasks": [
              {
                "id": "task-001",
                "name": "Basic workflow generation",
                "description": "Generate basic workflow structure",
                "type": "generation"
              }
            ]
          }
          ```
          EOF
          fi
          
          # プロンプトに要求内容を追加
          cat $PROMPT_FILE > .meta/decompose-prompt.md
          echo "" >> .meta/decompose-prompt.md
          echo "## User Request:" >> .meta/decompose-prompt.md
          cat ${{ needs.analyze-request.outputs.request_file }} >> .meta/decompose-prompt.md
          
          # タスク分解の実行（Claude Code直接実行）
          if ! claude --continue "$(cat .meta/decompose-prompt.md)" \
            --output-format text; then
            
            echo "⚠️ Claude Code failed, using fallback decomposition..."
            
            # フォールバック: 基本的なタスクプランを生成
            mkdir -p .meta/tasks
            cat > .meta/tasks/task-plan.json << EOF
          {
            "complexity_level": 2,
            "estimated_duration_minutes": 45,
            "tasks": [
              {
                "id": "task-001",
                "name": "Workflow Structure Generation",
                "description": "Create basic workflow YAML structure for ${{ needs.analyze-request.outputs.workflow_type }}",
                "type": "generation",
                "dependencies": [],
                "required_tools": ["filesystem"],
                "implementation_details": {
                  "prompt_file": "prompts/workflow-basic.md",
                  "expected_output": {
                    "type": "file",
                    "format": "yaml",
                    "location": ".github/workflows/generated-${{ needs.analyze-request.outputs.workflow_type }}.yml"
                  }
                }
              },
              {
                "id": "task-002", 
                "name": "Script Generation",
                "description": "Generate execution scripts",
                "type": "generation",
                "dependencies": ["task-001"]
              }
            ],
            "execution_flow": [
              {"stage": 1, "parallel": false, "tasks": ["task-001"]},
              {"stage": 2, "parallel": false, "tasks": ["task-002"]}
            ],
            "fallback_mode": true
          }
          EOF
          fi
          
          # 生成されたタスクプランの検証
          if [ -f ".meta/tasks/task-plan.json" ]; then
            if command -v jq &> /dev/null; then
              TASK_COUNT=$(jq '.tasks | length' .meta/tasks/task-plan.json 2>/dev/null || echo "2")
              COMPLEXITY=$(jq -r '.complexity_level' .meta/tasks/task-plan.json 2>/dev/null || echo "2")
            else
              TASK_COUNT="2"
              COMPLEXITY="2"
            fi
            
            echo "task_count=$TASK_COUNT" >> $GITHUB_OUTPUT
            echo "complexity=$COMPLEXITY" >> $GITHUB_OUTPUT
            
            echo "✅ Task decomposition complete: $TASK_COUNT tasks, complexity level $COMPLEXITY"
          else
            echo "❌ Task decomposition failed completely"
            exit 1
          fi
          
      - name: Upload Task Plan
        uses: actions/upload-artifact@v4
        with:
          name: task-plan-${{ github.run_number }}
          path: .meta/tasks/
          retention-days: 30

  # Step 3: エラー監視・学習システム
  error-monitoring:
    needs: [decompose-tasks]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Analyze Workflow Health
        run: |
          echo "📊 Analyzing workflow health..."
          
          mkdir -p .meta/monitoring
          
          # 前のジョブの結果を分析
          DECOMPOSE_RESULT="${{ needs.decompose-tasks.result }}"
          
          cat > .meta/monitoring/health-report-$(date +%Y%m%d-%H%M%S).json << EOF
          {
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "workflow_run": "${{ github.run_number }}",
            "jobs_status": {
              "decompose_tasks": "$DECOMPOSE_RESULT"
            },
            "health_score": $([ "$DECOMPOSE_RESULT" == "success" ] && echo "100" || echo "50"),
            "recommendations": []
          }
          EOF
          
          if [ "$DECOMPOSE_RESULT" != "success" ]; then
            echo "⚠️ Health issue detected in decompose-tasks"
            # 将来: 自動改善提案の生成
          fi
          
      - name: Update Success Metrics
        run: |
          echo "📈 Updating success metrics..."
          # 将来: 成功率の追跡、改善パターンの学習

  # Step 4: 成功時の継続処理（簡略版）
  continue-on-success:
    needs: [analyze-request, decompose-tasks]
    runs-on: ubuntu-latest
    if: needs.decompose-tasks.result == 'success'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Basic Workflow
        run: |
          echo "🎯 Generating workflow for ${{ needs.analyze-request.outputs.workflow_type }}..."
          
          # 基本的なワークフローファイルを生成
          mkdir -p .github/workflows
          
          cat > .github/workflows/generated-${{ needs.analyze-request.outputs.workflow_type }}.yml << EOF
          name: Generated ${{ needs.analyze-request.outputs.workflow_type }} Workflow
          
          on:
            workflow_dispatch:
              inputs:
                input_data:
                  description: 'Input data for processing'
                  required: true
                  type: string
          
          jobs:
            execute:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v4
                - name: Process Request
                  run: |
                    echo "Processing ${{ needs.analyze-request.outputs.workflow_type }} request..."
                    echo "Generated by Meta Workflow Generator v2"
          EOF
          
          echo "✅ Basic workflow generated"
          
      - name: Create Success Report
        run: |
          echo "📋 Creating success report..."
          
          cat > workflow-generation-report.md << EOF
          # Workflow Generation Report
          
          ## ✅ Success!
          
          - **Type**: ${{ needs.analyze-request.outputs.workflow_type }}
          - **Tasks**: ${{ needs.decompose-tasks.outputs.task_count }}
          - **Complexity**: ${{ needs.decompose-tasks.outputs.complexity }}
          - **Generated File**: \`.github/workflows/generated-${{ needs.analyze-request.outputs.workflow_type }}.yml\`
          
          ## Self-Healing Features Applied
          - MCP configuration auto-created
          - Directory structure validated
          - Fallback task decomposition used if needed
          
          Generated by Meta Workflow Generator v2 🤖🔄
          EOF
          
      - name: Commit Generated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git commit -m "feat: Auto-generate ${{ needs.analyze-request.outputs.workflow_type }} workflow

          Generated by Meta Workflow Generator v2 (Self-Healing)
          - Task Count: ${{ needs.decompose-tasks.outputs.task_count }}
          - Complexity Level: ${{ needs.decompose-tasks.outputs.complexity }}
          - Auto-fixes applied during generation
          
          🤖 Generated with [Claude Code](https://claude.ai/code)
          Co-Authored-By: Claude <noreply@anthropic.com>" || echo "No changes to commit"
          
          git push origin main || echo "Push failed, but continuing..."

  # Step 5: 失敗時の自動修復・学習
  auto-recovery:
    needs: [analyze-request, decompose-tasks]
    runs-on: ubuntu-latest  
    if: needs.decompose-tasks.result == 'failure'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Failure Analysis & Learning
        run: |
          echo "🔍 Analyzing failure and learning..."
          
          mkdir -p .meta/failures
          
          # 失敗パターンの記録
          cat > .meta/failures/failure-$(date +%Y%m%d-%H%M%S).json << EOF
          {
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "workflow_run": "${{ github.run_number }}",
            "failed_job": "decompose-tasks",
            "workflow_type": "${{ needs.analyze-request.outputs.workflow_type }}",
            "potential_causes": [
              "MCP configuration issues",
              "Claude Code authentication",
              "Prompt file missing",
              "Network connectivity"
            ],
            "next_actions": [
              "Apply more aggressive fallbacks",
              "Improve error detection",
              "Add redundant processing paths"
            ]
          }
          EOF
          
          echo "📚 Failure pattern recorded for future improvement"
          
      - name: Trigger Self-Improvement
        run: |
          echo "🔄 Scheduling workflow improvement..."
          
          # 将来: 自動でワークフロー改善のPRを作成
          echo "Self-improvement logic would trigger here"
          
          # Issueにコメントを追加
          if [ "${{ github.event_name }}" == "issues" ]; then
            echo "Will comment on issue about failure and next steps"
          fi