name: "Test MCP Method Patterns"
run-name: "🧪 Testing MCP Method Call Patterns"

on:
  workflow_dispatch:

jobs:
  test-method-patterns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Test Available MCP Methods
        uses: anthropics/claude-code-base-action@beta
        env:
          CLAUDE_CODE_CI_MODE: "true"
          CLAUDE_CODE_AUTO_APPROVE_MCP: "true"
        with:
          prompt: |
            Analyze available MCP methods:
            1. List all available MCP tools that start with mcp__
            2. For i2v-fal-hailuo-02-pro, list all available methods
            3. Compare with t2i-google-imagen3 methods
            4. Save analysis to mcp-methods-analysis.txt
          system_prompt: |
            Analyzing MCP service methods to understand differences.
          mcp_config: ".claude/mcp-kamuicode.json"
          allowed_tools: "Write"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
      - name: Test Submit vs Other Methods
        uses: anthropics/claude-code-base-action@beta
        env:
          CLAUDE_CODE_CI_MODE: "true"
          CLAUDE_CODE_AUTO_APPROVE_MCP: "true"
        with:
          prompt: |
            Test different method patterns:
            1. For t2i-google-imagen3, what methods are available?
            2. For i2v-fal-hailuo-02-pro, try calling status or result method first
            3. Document which methods require permission
            4. Save to method-permission-test.txt
          system_prompt: |
            Testing if certain methods bypass permission requirements.
          mcp_config: ".claude/mcp-kamuicode.json"
          allowed_tools: "mcp__t2i-google-imagen3__*,mcp__i2v-fal-hailuo-02-pro__*,Write"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
      - name: Upload analysis
        uses: actions/upload-artifact@v4
        with:
          name: method-analysis-${{ github.run_number }}
          path: |
            mcp-methods-analysis.txt
            method-permission-test.txt