name: "Test MCP Permissions"
run-name: "🧪 Testing MCP Permission Settings"

on:
  workflow_dispatch:

jobs:
  test-mcp-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Test 1 - With CI Mode and Auto Approve
        uses: anthropics/claude-code-base-action@beta
        env:
          CLAUDE_CODE_CI_MODE: "true"
          CLAUDE_CODE_AUTO_APPROVE_MCP: "true"
        with:
          prompt: |
            Test MCP access:
            1. List available MCP services
            2. Try to use t2i-google-imagen3 to generate a test image
            3. Report if permission is needed or granted
          system_prompt: |
            You are testing MCP permissions in CI/CD.
            Report what happens when you try to use MCP services.
          mcp_config: ".claude/mcp-kamuicode.json"
          allowed_tools: "View,mcp__t2i-google-imagen3__*,Bash,Write"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
      - name: Test 2 - With Different Env Vars
        uses: anthropics/claude-code-base-action@beta
        env:
          CLAUDE_CODE_CI: "true"
          CLAUDE_CODE_HEADLESS: "true"
          CLAUDE_CODE_NON_INTERACTIVE: "true"
        with:
          prompt: |
            Test MCP access with different env vars:
            1. Try to use t2i-google-imagen3
            2. Report the result
          system_prompt: |
            Testing alternative environment variables for CI/CD.
          mcp_config: ".claude/mcp-kamuicode.json"
          allowed_tools: "View,mcp__t2i-google-imagen3__*,Bash,Write"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
      - name: Test 3 - With Settings Parameter
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            Test MCP with settings parameter:
            1. Try to use t2i-google-imagen3
            2. Report the result
          system_prompt: |
            Testing with settings parameter approach.
          mcp_config: ".claude/mcp-kamuicode.json"
          allowed_tools: "View,mcp__t2i-google-imagen3__*,Bash,Write"
          settings: |
            {
              "alwaysApproveTools": true,
              "autoApprovePermissions": true,
              "enableAllProjectMcpServers": true
            }
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}