name: Test Recovery Workflow
on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Test name'
        required: true
        default: 'Test'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Testing recovery features for ${{ inputs.test_name }}"
