name: "Test MCP with Full Permissions"
run-name: "🧪 Testing MCP with settings.local.json permissions"

on:
  workflow_dispatch:

jobs:
  test-with-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Claude settings directory
        run: |
          echo "📁 Setting up Claude settings..."
          mkdir -p ~/.claude
          
      - name: Copy permissions settings to Claude directory
        run: |
          echo "📋 Copying settings with MCP permissions..."
          # Copy the settings.local.json to where Claude Code expects it
          cp .claude/settings.local.json ~/.claude/settings.json
          
          # Also try in the project-specific location
          PROJECT_DIR="$HOME/.claude/projects/$(pwd | sed 's|/|-|g')"
          mkdir -p "$PROJECT_DIR"
          cp .claude/settings.local.json "$PROJECT_DIR/settings.json"
          
          echo "✅ Settings copied to:"
          echo "  - ~/.claude/settings.json"
          echo "  - $PROJECT_DIR/settings.json"
          
      - name: Test Image Generation with Permissions
        uses: anthropics/claude-code-base-action@beta
        env:
          CLAUDE_CODE_CI_MODE: "true"
          CLAUDE_CODE_AUTO_APPROVE_MCP: "true"
        with:
          prompt: |
            Test MCP with pre-configured permissions:
            1. Use t2i-fal-imagen4-fast to generate "A golden sunset over mountains"
            2. Report if permission is still required or if it works
            3. Save result to test-with-permissions.txt
          system_prompt: |
            Testing with pre-loaded permissions from settings.local.json
          mcp_config: ".claude/mcp-kamuicode.json"
          settings: ".claude/settings.local.json"
          allowed_tools: "mcp__t2i-fal-imagen4-fast__*,Write,Read"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
      - name: Test Video Generation with Permissions
        uses: anthropics/claude-code-base-action@beta
        env:
          CLAUDE_CODE_CI_MODE: "true"
          CLAUDE_CODE_AUTO_APPROVE_MCP: "true"
        with:
          prompt: |
            Test I2V with pre-configured permissions:
            1. Try i2v-fal-hailuo-02-pro with test parameters
            2. Report if it works or still needs permission
            3. Save to test-video-permissions.txt
          system_prompt: |
            Testing video generation with pre-loaded permissions
          mcp_config: ".claude/mcp-kamuicode.json"
          settings: ".claude/settings.local.json"
          allowed_tools: "mcp__i2v-fal-hailuo-02-pro__*,Write"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
      - name: Alternative - Inline Settings Test
        uses: anthropics/claude-code-base-action@beta
        env:
          CLAUDE_CODE_CI_MODE: "true"
          CLAUDE_CODE_AUTO_APPROVE_MCP: "true"
          CLAUDE_SETTINGS_JSON: |
            {
              "permissions": {
                "allow": [
                  "mcp__t2i-google-imagen3__imagen_t2i",
                  "mcp__t2i-fal-imagen4-fast__imagen4_fast_submit",
                  "mcp__t2i-fal-imagen4-fast__imagen4_fast_result",
                  "mcp__i2v-fal-hailuo-02-pro__hailuo_02_submit",
                  "mcp__i2v-fal-hailuo-02-pro__hailuo_02_result"
                ]
              }
            }
        with:
          prompt: |
            Test with inline permissions:
            1. Generate image with t2i-fal-imagen4-fast
            2. Report results to test-inline-permissions.txt
          system_prompt: |
            Testing with inline permission configuration
          mcp_config: ".claude/mcp-kamuicode.json"
          allowed_tools: "mcp__t2i-fal-imagen4-fast__*,Write"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: permission-test-results-${{ github.run_number }}
          path: test-*.txt